In [1]:
import pandas as pd

df = pd.read_csv("../raw/Vittime.tipo_violenza.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,TYPE_VIOLENCE,Tipo_di_violenza,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2015.0,67.0,NaN,NaN
1,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2016.0,80.0,NaN,NaN
2,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2017.0,66.0,NaN,NaN
3,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2018.0,82.0,NaN,NaN
4,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2019.0,62.0,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 108
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,PHY,Violenza fisica,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,PHYVIOL,Violenza psicologica,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,PHYVIOL,Violenza psicologica,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ECON_VIOL,Violenza economica,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,UNAV,Non disponibile,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2015,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2017,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2021,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2022,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHY,Violenza fisica,2024,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,SEXVIOL,Violenza sessuale,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,SEXVIOL,Violenza sessuale,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,SEXVIOL,Violenza sessuale,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,SEXVIOL,Violenza sessuale,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,SEXVIOL,Violenza sessuale,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,THREATS,Minacce,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,HARASS_WORK,Mobbing,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2017,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2018,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2019,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2020,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,PHYVIOL,Violenza psicologica,2024,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,STLK,Atti persecutori/ stalking,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,STLK,Atti persecutori/ stalking,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2017,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2018,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2022,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2024,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,ALL,Tutte le voci,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2015,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2017,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2018,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2021,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2022,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHY,Violenza fisica,2024,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,SEXVIOL,Violenza sessuale,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,SEXVIOL,Violenza sessuale,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,SEXVIOL,Violenza sessuale,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,SEXVIOL,Violenza sessuale,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,SEXVIOL,Violenza sessuale,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,THREATS,Minacce,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,HARASS_WORK,Mobbing,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2017,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2018,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2019,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2020,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,PHYVIOL,Violenza psicologica,2024,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ECON_VIOL,Violenza economica,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,STLK,Atti persecutori/ stalking,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,STLK,Atti persecutori/ stalking,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2017,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2018,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2022,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2024,24,,']


============================================================
Colonna: Frequenza
Numero valori unici: 2
Valori unici:
['Annuale' nan]


============================================================
Colonna: REF_AREA
Numero valori unici: 29
Valori unici:
['IT' 'ITC' 'ITC1' nan 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 29
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' nan 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 2
Valori unici:
['VICTIMS' nan]


============================================================
Colonna: Indicatore
Numero valori unici: 2
Valori unici:
['Vittime di violenza' nan]


============================================================
Colonna: SEX
Numero valori unici: 5
Valori unici:
['M' 'F' 'NRP' 'T' nan]


============================================================
Colonna: Sesso
Numero valori unici: 5
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale' nan]


============================================================
Colonna: TYPE_VIOLENCE
Numero valori unici: 17
Valori unici:
['PHY' 'SEXVIOL' 'THREATS' 'HARASS_WORK' 'DIS_SEX_EXPL' 'PHYVIOL'
 'ECON_VIOL' 'STLK' 'ONL_VIOL' 'OTH' 'NRP' 'UNAV' 'ALL' 'TRAFF'
 'EXPLOI_PROST' 'FMARR' nan]


============================================================
Colonna: Tipo_di_violenza
Numero valori unici: 17
Valori unici:
['Violenza fisica' 'Violenza sessuale' 'Minacce' 'Mobbing'
 'Diffusione illecita di immagini o di video sessualmente espliciti'
 'Violenza psicologica' 'Violenza economica' 'Atti persecutori/ stalking'
 'Violenza digitale' 'Altro' 'Non risponde' 'Non disponibile'
 'Tutte le voci' 'Tratta' 'Sfruttamento della prostituzione'
 'Matrimonio forzato' nan]


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 11
Valori unici:
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.   nan]


============================================================
Colonna: Osservazione
Numero valori unici: 964
Valori unici:
[6.7000e+01 8.0000e+01 6.6000e+01 8.2000e+01 6.2000e+01 1.8900e+02
 1.5800e+02 1.4600e+02 1.6200e+02 2.3000e+01 2.9000e+01 4.5000e+01
 2.5000e+01 9.4000e+01 1.1600e+02 4.2000e+01 2.4000e+01 1.4000e+01
 1.9000e+01 1.3000e+01 1.2000e+01 2.6000e+01 3.2000e+01 2.1000e+01
 5.0000e+00 8.0000e+00 3.0000e+00 1.0000e+00 4.0000e+00 7.0000e+00
 1.3400e+02 1.2800e+02 1.0700e+02 1.8200e+02 1.4800e+02 7.4000e+01
 1.4000e+02 1.5400e+02 2.0000e+00 9.0000e+00 7.6000e+01 2.0000e+01
 1.0000e+01 1.1000e+01 6.0000e+00 2.7000e+01 3.8000e+01 1.8000e+01
 4.4000e+01 6.4000e+01 2.8000e+01 3.1100e+02 2.9500e+02 2.8600e+02
 2.6100e+02 2.1800e+02 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02
 4.3300e+02 3.6930e+03 3.7270e+03 3.5530e+03 4.1660e+03 3.6980e+03
 7.2500e+03 6.9490e+03 5.0240e+03 6.6620e+03 7.1260e+03 2.5800e+02
 3.2700e+02 4.9300e+02 4.1200e+02 4.7900e+02 1.0400e+03 1.4060e+03
 8.5700e+02 6.7300e+02 5.9800e+02 2.8100e+02 3.2500e+02 3.3700e+02
 3.6200e+02 4.8200e+02 7.5500e+02 6.1000e+02 1.1900e+02 1.5000e+01
 5.9000e+01 4.0000e+01 2.2000e+01 3.0000e+01 2.7840e+03 2.8370e+03
 2.7320e+03 3.6400e+03 3.2630e+03 5.1340e+03 5.2400e+03 3.8180e+03
 5.2670e+03 6.1940e+03 1.3900e+02 1.4700e+02 1.4300e+02 1.2200e+02
 1.1300e+02 1.8000e+02 1.2500e+02 1.0900e+03 1.5130e+03 1.4100e+02
 9.6000e+01 6.8000e+01 4.7000e+01 1.9900e+02 1.5500e+02 1.5300e+02
 7.8000e+01 4.5000e+02 3.5200e+02 4.3200e+02 5.4300e+02 5.0100e+02
 7.8400e+02 9.8900e+02 1.0040e+03 3.4400e+02 2.5100e+02 7.7700e+03
 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04
 1.1632e+04 1.4455e+04 1.6117e+04 1.2960e+03 1.0170e+03 1.4030e+03
 1.0810e+03 3.7600e+03 3.8070e+03 3.6190e+03 4.2480e+03 7.4390e+03
 7.1070e+03 5.1040e+03 6.8760e+03 7.3300e+03 3.5600e+02 5.3800e+02
 4.3700e+02 5.0400e+02 1.1340e+03 1.5220e+03 8.9900e+02 7.0000e+02
 6.1300e+02 3.0600e+02 3.5000e+02 3.7500e+02 3.2300e+02 5.0800e+02
 7.8700e+02 6.3100e+02 1.2600e+02 1.7000e+02 3.3000e+01 3.1000e+01
 1.6000e+01 6.3000e+01 7.9000e+01 4.1000e+01 3.7000e+01 2.9180e+03
 2.9650e+03 2.8390e+03 3.7470e+03 3.3430e+03 5.3160e+03 5.3880e+03
 3.8920e+03 5.4210e+03 6.3570e+03 1.5100e+02 1.4500e+02 1.2300e+02
 1.1800e+02 1.8500e+02 1.5600e+02 1.2700e+02 1.0100e+02 1.1800e+03
 1.5940e+03 1.6100e+02 1.0600e+02 9.1000e+01 7.5000e+01 5.3000e+01
 2.2600e+02 1.6300e+02 1.6700e+02 9.0000e+01 4.8900e+02 3.7000e+02
 4.6400e+02 5.6600e+02 5.3000e+02 8.3700e+02 1.0650e+03 1.0470e+03
 1.6470e+03 1.2750e+03 8.0820e+03 8.1250e+03 8.0850e+03 9.6020e+03
 8.6470e+03 1.5708e+04 1.6272e+04 1.1909e+04 1.6283e+04 1.7631e+04
 1.7000e+01 7.2000e+01 7.1000e+01 6.1000e+01 5.6000e+01 1.0200e+02
 1.0300e+02 5.1000e+01 9.6400e+02 1.0800e+03 9.5200e+02 1.0450e+03
 9.3900e+02 1.7410e+03 1.6310e+03 1.2640e+03 1.5060e+03 1.9040e+03
 8.9000e+01 1.1200e+02 2.4500e+02 3.3400e+02 2.3100e+02 1.6500e+02
 1.9500e+02 7.3000e+01 8.4000e+01 8.8000e+01 7.7000e+01 1.0900e+02
 1.8100e+02 1.6000e+02 7.8500e+02 8.4600e+02 7.7800e+02 9.3200e+02
 8.8700e+02 1.3100e+03 1.2230e+03 1.0050e+03 1.3170e+03 1.6300e+03
 4.3000e+01 3.5000e+01 2.7300e+02 4.4600e+02 3.4000e+01 8.5000e+01
 6.9000e+01 6.5000e+01 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 5.0000e+01 3.9000e+01 7.0000e+01 9.7800e+02 1.1020e+03 9.7700e+02
 1.0620e+03 9.5700e+02 1.7700e+03 1.6640e+03 1.2780e+03 1.5510e+03
 1.9420e+03 2.6000e+02 3.5700e+02 2.3500e+02 1.7300e+02 1.9700e+02
 8.1000e+01 9.5000e+01 1.8800e+02 5.2000e+01 8.2300e+02 8.7300e+02
 7.9600e+02 9.5900e+02 9.0900e+02 1.3550e+03 1.2540e+03 1.0190e+03
 1.3530e+03 1.6670e+03 2.8700e+02 4.6500e+02 5.7000e+01 2.1490e+03
 2.2770e+03 2.1460e+03 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03
 2.8450e+03 3.5500e+03 4.4750e+03 3.6000e+01 3.3200e+02 2.8300e+02

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",         
    "SEX",                
    "TYPE_VIOLENCE",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (6683, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Tipo_di_violenza', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Tipo_di_violenza": "tipo_violenza",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: tipo_violenza
['Violenza fisica' 'Violenza sessuale' 'Minacce' 'Mobbing'
 'Diffusione illecita di immagini o di video sessualmente espliciti'
 'Violenza psicologica' 'Violenza economica' 'Atti persecutori/ stalking'
 'Violenza digitale' 'Altro' 'Non risponde' 'Non disponibile'
 'Tutte le voci' 'Tratta' 'Sfruttamento della prostituzione'
 'Matrimonio forzato']

Colonna: periodo
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.]

Colonna: numero_vittime
[6.7000e+01 8.0000e+01 6.6000e+01 8.2000e+01 6.2000e+01 1.8900e+02
 1.5800e+02 1.4600e+02 1.6200e+02 2.3000e+01 2.9000e+01 4.5000e+01
 2.5000e+01 9.4000e+01 1.1600e+02 4.2000e+01 2.4000e+01 1.4000e+01
 1.9000e+01 1.3000e+01 1.2000e+01 2.6000e+01 3.2000e+01 2.1000e+01
 5.0000e+00 8.0000e+00 3.0000e+00 1.0000e+00 4.0000e+00 7.0000e+00
 1.3400e+02 1.2800e+02 1.0700e+02 1.8200e+02 1.4800e+02 7.4000e+01
 1.4000e+02 1.5400e+02 2.0000e+00 9.0000e+00 7.6000e+01 2.0000e+01
 1.0000e+01 1.1000e+01 6.0000e+00 2.7000e+01 3.8000e+01 1.8000e+01
 4.4000e+01 6.4000e+01 2.8000e+01 3.1100e+02 2.9500e+02 2.8600e+02
 2.6100e+02 2.1800e+02 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02
 4.3300e+02 3.6930e+03 3.7270e+03 3.5530e+03 4.1660e+03 3.6980e+03
 7.2500e+03 6.9490e+03 5.0240e+03 6.6620e+03 7.1260e+03 2.5800e+02
 3.2700e+02 4.9300e+02 4.1200e+02 4.7900e+02 1.0400e+03 1.4060e+03
 8.5700e+02 6.7300e+02 5.9800e+02 2.8100e+02 3.2500e+02 3.3700e+02
 3.6200e+02 4.8200e+02 7.5500e+02 6.1000e+02 1.1900e+02 1.5000e+01
 5.9000e+01 4.0000e+01 2.2000e+01 3.0000e+01 2.7840e+03 2.8370e+03
 2.7320e+03 3.6400e+03 3.2630e+03 5.1340e+03 5.2400e+03 3.8180e+03
 5.2670e+03 6.1940e+03 1.3900e+02 1.4700e+02 1.4300e+02 1.2200e+02
 1.1300e+02 1.8000e+02 1.2500e+02 1.0900e+03 1.5130e+03 1.4100e+02
 9.6000e+01 6.8000e+01 4.7000e+01 1.9900e+02 1.5500e+02 1.5300e+02
 7.8000e+01 4.5000e+02 3.5200e+02 4.3200e+02 5.4300e+02 5.0100e+02
 7.8400e+02 9.8900e+02 1.0040e+03 3.4400e+02 2.5100e+02 7.7700e+03
 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04
 1.1632e+04 1.4455e+04 1.6117e+04 1.2960e+03 1.0170e+03 1.4030e+03
 1.0810e+03 3.7600e+03 3.8070e+03 3.6190e+03 4.2480e+03 7.4390e+03
 7.1070e+03 5.1040e+03 6.8760e+03 7.3300e+03 3.5600e+02 5.3800e+02
 4.3700e+02 5.0400e+02 1.1340e+03 1.5220e+03 8.9900e+02 7.0000e+02
 6.1300e+02 3.0600e+02 3.5000e+02 3.7500e+02 3.2300e+02 5.0800e+02
 7.8700e+02 6.3100e+02 1.2600e+02 1.7000e+02 3.3000e+01 3.1000e+01
 1.6000e+01 6.3000e+01 7.9000e+01 4.1000e+01 3.7000e+01 2.9180e+03
 2.9650e+03 2.8390e+03 3.7470e+03 3.3430e+03 5.3160e+03 5.3880e+03
 3.8920e+03 5.4210e+03 6.3570e+03 1.5100e+02 1.4500e+02 1.2300e+02
 1.1800e+02 1.8500e+02 1.5600e+02 1.2700e+02 1.0100e+02 1.1800e+03
 1.5940e+03 1.6100e+02 1.0600e+02 9.1000e+01 7.5000e+01 5.3000e+01
 2.2600e+02 1.6300e+02 1.6700e+02 9.0000e+01 4.8900e+02 3.7000e+02
 4.6400e+02 5.6600e+02 5.3000e+02 8.3700e+02 1.0650e+03 1.0470e+03
 1.6470e+03 1.2750e+03 8.0820e+03 8.1250e+03 8.0850e+03 9.6020e+03
 8.6470e+03 1.5708e+04 1.6272e+04 1.1909e+04 1.6283e+04 1.7631e+04
 1.7000e+01 7.2000e+01 7.1000e+01 6.1000e+01 5.6000e+01 1.0200e+02
 1.0300e+02 5.1000e+01 9.6400e+02 1.0800e+03 9.5200e+02 1.0450e+03
 9.3900e+02 1.7410e+03 1.6310e+03 1.2640e+03 1.5060e+03 1.9040e+03
 8.9000e+01 1.1200e+02 2.4500e+02 3.3400e+02 2.3100e+02 1.6500e+02
 1.9500e+02 7.3000e+01 8.4000e+01 8.8000e+01 7.7000e+01 1.0900e+02
 1.8100e+02 1.6000e+02 7.8500e+02 8.4600e+02 7.7800e+02 9.3200e+02
 8.8700e+02 1.3100e+03 1.2230e+03 1.0050e+03 1.3170e+03 1.6300e+03
 4.3000e+01 3.5000e+01 2.7300e+02 4.4600e+02 3.4000e+01 8.5000e+01
 6.9000e+01 6.5000e+01 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 5.0000e+01 3.9000e+01 7.0000e+01 9.7800e+02 1.1020e+03 9.7700e+02
 1.0620e+03 9.5700e+02 1.7700e+03 1.6640e+03 1.2780e+03 1.5510e+03
 1.9420e+03 2.6000e+02 3.5700e+02 2.3500e+02 1.7300e+02 1.9700e+02
 8.1000e+01 9.5000e+01 1.8800e+02 5.2000e+01 8.2300e+02 8.7300e+02
 7.9600e+02 9.5900e+02 9.0900e+02 1.3550e+03 1.2540e+03 1.0190e+03
 1.3530e+03 1.6670e+03 2.8700e+02 4.6500e+02 5.7000e+01 2.1490e+03
 2.2770e+03 2.1460e+03 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03
 2.8450e+03 3.5500e+03 4.4750e+03 3.6000e+01 3.3200e+02 2.8300e+02
 2.9600e+02 4.9100e+02 4.2900e+02 3.1200e+02 3.9200e+02 4.9000e+02
 5.4000e+01 4.8000e+01 4.6000e+01 2.5700e+02 2.7100e+02 2.3000e+02
 3.0900e+02 3.5100e+02 2.9900e+02 3.7400e+02 3.9900e+02 6.4500e+02
 6.8400e+02 6.2300e+02 7.0900e+02 6.3200e+02 9.8500e+02 7.4700e+02
 9.1100e+02 1.0760e+03 3.0100e+02 3.4300e+02 2.9400e+02 2.9800e+02
 2.8800e+02 5.0000e+02 4.4200e+02 3.1600e+02 4.0200e+02 4.9600e+02
 2.7000e+02 2.7600e+02 2.3600e+02 2.6600e+02 3.6400e+02 3.0200e+02
 3.8400e+02 4.0900e+02 1.1100e+02 6.6900e+02 7.0300e+02 6.5100e+02
 7.2200e+02 6.4700e+02 1.0110e+03 9.8800e+02 7.5900e+02 9.4800e+02
 1.1120e+03 1.0500e+02 1.4200e+02 1.1500e+02 1.6400e+02 8.6000e+01
 1.1000e+02 8.7000e+01 1.3600e+02 2.0500e+02 2.0900e+02 1.8300e+02
 2.2800e+02 1.8400e+02 3.0700e+02 3.1000e+02 2.6300e+02 3.6000e+02
 9.7000e+01 1.2000e+02 1.6600e+02 1.1400e+02 2.1200e+02 2.1500e+02
 2.3400e+02 3.2200e+02 3.1900e+02 2.7700e+02 5.8000e+01 5.5000e+01
 5.5800e+02 6.4900e+02 5.9700e+02 6.2800e+02 5.7800e+02 1.1040e+03
 1.0570e+03 8.4500e+02 9.9800e+02 1.2410e+03 4.9000e+01 2.1600e+02
 1.5000e+02 1.3000e+02 1.0000e+02 4.5200e+02 4.5700e+02 5.3500e+02
 5.4400e+02 8.3300e+02 7.6200e+02 6.1700e+02 8.3900e+02 1.0860e+03
 3.1700e+02 1.2150e+03 1.3090e+03 1.2600e+03 1.3740e+03 1.3340e+03
 2.2630e+03 2.2640e+03 1.8020e+03 2.2040e+03 2.8770e+03 5.6500e+02
 6.5700e+02 6.4100e+02 5.8900e+02 1.1240e+03 1.0770e+03 8.5300e+02
 1.0280e+03 1.2700e+03 8.3000e+01 1.6800e+02 2.3200e+02 1.1700e+02
 1.3200e+02 6.0000e+01 4.7300e+02 4.6700e+02 5.5200e+02 8.6000e+02
 7.7500e+02 6.2700e+02 8.6200e+02 1.1070e+03 1.2560e+03 1.3480e+03
 1.2970e+03 1.4150e+03 1.3700e+03 2.3240e+03 2.3220e+03 1.8350e+03
 2.3180e+03 2.9690e+03 4.8800e+02 4.7400e+02 4.3600e+02 5.4500e+02
 5.2700e+02 1.0360e+03 7.7100e+02 9.7400e+02 1.2890e+03 2.4000e+02
 1.4400e+02 5.2500e+02 4.6100e+02 7.1900e+02 7.8900e+02 6.0700e+02
 8.2200e+02 1.1920e+03 1.7500e+02 3.3000e+02 1.0260e+03 1.0090e+03
 9.7500e+02 1.2550e+03 1.1960e+03 2.0050e+03 2.2780e+03 1.7020e+03
 2.1750e+03 3.0120e+03 4.9700e+02 4.4000e+02 5.3900e+02 9.7000e+02
 1.0550e+03 7.8200e+02 1.0060e+03 1.3180e+03 3.9700e+02 3.7100e+02
 5.3200e+02 4.7100e+02 7.4000e+02 8.0100e+02 6.1800e+02 8.4300e+02
 1.2080e+03 1.9000e+02 3.4200e+02 1.0750e+03 1.0480e+03 1.2860e+03
 1.2280e+03 2.0830e+03 2.3390e+03 1.7310e+03 2.2710e+03 3.1140e+03
 2.3800e+02 2.2300e+02 2.7400e+02 4.9400e+02 6.1900e+02 1.7900e+02
 1.5900e+02 2.4700e+02 3.2800e+02 2.7800e+02 3.6600e+02 5.2800e+02
 4.8000e+02 4.6800e+02 4.7500e+02 6.1400e+02 6.1100e+02 9.5600e+02
 1.1410e+03 8.6100e+02 1.0140e+03 1.3930e+03 2.1900e+02 2.2400e+02
 2.8000e+02 5.3700e+02 4.1600e+02 5.0900e+02 6.3400e+02 1.7400e+02
 3.7600e+02 2.8200e+02 4.8600e+02 6.2600e+02 9.9200e+02 1.1690e+03
 8.7100e+02 1.0560e+03 1.4360e+03 1.3500e+02 1.6900e+02 1.3700e+02
 1.0800e+02 1.7100e+02 2.6900e+02 2.0100e+02 2.0200e+02 2.2000e+02
 2.0400e+02 4.0100e+02 3.6100e+02 5.2600e+02 1.8700e+02 3.2600e+02
 4.2300e+02 3.9400e+02 5.1300e+02 8.8200e+02 9.6500e+02 7.1000e+02
 2.0300e+02 2.0600e+02 4.0800e+02 2.2200e+02 1.9100e+02 3.3300e+02
 3.6300e+02 4.7600e+02 4.5600e+02 4.4300e+02 4.1300e+02 5.2200e+02
 9.1300e+02 9.9400e+02 7.2700e+02 8.9400e+02 8.0200e+02 6.9900e+02
 9.1000e+02 8.2900e+02 1.5340e+03 1.5520e+03 1.2160e+03 1.4970e+03
 1.6530e+03 1.7700e+02 1.2400e+02 1.5200e+02 6.6100e+02 6.4200e+02
 8.6700e+02 8.2400e+02 1.0680e+03 1.1790e+03 8.7700e+02 1.0580e+03
 1.3500e+03 1.7150e+03 1.6780e+03 1.5700e+03 2.0960e+03 1.9410e+03
 3.0530e+03 3.3850e+03 2.5730e+03 3.0620e+03 3.5730e+03 8.1800e+02
 7.9900e+02 7.1500e+02 9.2900e+02 1.5800e+03 1.5850e+03 1.2370e+03
 1.5490e+03 1.6940e+03 1.2100e+02 2.1400e+02 3.4600e+02 1.9300e+02
 9.2000e+01 6.8700e+02 6.7200e+02 8.9300e+02 1.1080e+03 1.2070e+03
 1.0850e+03 1.3800e+03 2.5000e+02 3.4100e+02 9.3000e+01 1.7710e+03
 1.7540e+03 1.6330e+03 2.1530e+03 1.9890e+03 3.1830e+03 3.4870e+03
 2.6430e+03 3.2130e+03 3.7240e+03 2.2700e+02 2.0800e+02 2.9000e+02
 3.5300e+02 4.5500e+02 2.2500e+02 3.0400e+02 2.5200e+02 3.8000e+02
 3.7900e+02 4.2700e+02 5.5900e+02 5.1600e+02 8.2700e+02 6.1600e+02
 7.2400e+02 9.9500e+02 1.9600e+02 4.3000e+02 3.8700e+02 2.9700e+02
 4.6300e+02 2.4300e+02 3.0300e+02 2.5900e+02 3.8900e+02 5.7300e+02
 5.1900e+02 8.6900e+02 8.5800e+02 6.3800e+02 1.0340e+03 9.9000e+01
 1.4900e+02 1.7200e+02 2.0000e+02 2.8500e+02 2.5600e+02 2.6700e+02
 9.8000e+01 1.3800e+02 2.2100e+02 2.6400e+02 2.7900e+02 3.7800e+02
 4.7200e+02 4.8700e+02 4.9200e+02 9.0000e+02 7.3200e+02 8.9800e+02
 9.3700e+02 1.9400e+02 3.8200e+02 4.0400e+02 4.8300e+02 6.2100e+02
 6.7000e+02 6.6200e+02 7.4500e+02 8.7200e+02 1.1950e+03 1.1450e+03
 1.7970e+03 2.0440e+03 1.8750e+03 4.9800e+02 3.8100e+02 5.4600e+02
 9.2500e+02 9.8300e+02 7.4200e+02 9.6300e+02 3.4500e+02 6.4300e+02
 6.8600e+02 5.4800e+02 6.7600e+02 7.6300e+02 1.5700e+02 1.1010e+03
 9.0500e+02 1.2320e+03 1.1820e+03 1.8690e+03 2.1040e+03 1.5870e+03
 1.9750e+03 2.0920e+03 9.2700e+02 7.9700e+02 1.5020e+03 1.4640e+03
 1.0390e+03 1.3610e+03 6.1500e+02 7.5700e+02 8.1000e+02 1.0660e+03
 1.8100e+03 1.7100e+03 1.5410e+03 2.0370e+03 1.8060e+03 2.8820e+03
 3.0050e+03 2.1960e+03 2.3770e+03 9.4500e+02 8.7400e+02 8.0600e+02
 1.0250e+03 8.5600e+02 1.5360e+03 1.4880e+03 1.0520e+03 1.2460e+03
 1.4090e+03 2.3300e+02 6.0600e+02 5.1200e+02 7.8600e+02 7.2000e+02
 7.9000e+02 1.0940e+03 1.8830e+03 1.7760e+03 1.5930e+03 2.0990e+03
 1.8490e+03 2.9640e+03 3.0890e+03 2.2340e+03 2.4810e+03 1.2900e+02
 2.1700e+02 2.8900e+02 2.7200e+02 1.0400e+02 1.8600e+02 2.3900e+02
 2.7500e+02 4.6200e+02 3.9500e+02 3.8600e+02 6.9300e+02 6.8500e+02
 8.3000e+02 9.6000e+02 1.2950e+03 1.3720e+03 9.6800e+02 1.0330e+03
 1.2870e+03 4.6600e+02 4.4100e+02 5.2900e+02 3.8800e+02 7.0400e+02
 6.9100e+02 5.0200e+02 5.6400e+02 6.5600e+02 3.3500e+02 4.1900e+02
 9.0400e+02 9.9000e+02 8.6400e+02 1.3230e+03 1.4070e+03 9.9100e+02
 1.0830e+03 1.3450e+03 2.4800e+02 4.0600e+02 4.1700e+02 4.1800e+02
 3.1400e+02 2.5500e+02 4.9500e+02 4.4800e+02 4.1400e+02 5.9000e+02
 8.2000e+02 8.7900e+02 6.3500e+02 6.7800e+02 8.8900e+02 4.2800e+02
 3.2000e+02 2.4100e+02 8.5200e+02 9.0200e+02 7.0600e+02 3.2400e+02
 1.3300e+02 3.5900e+02 3.4000e+02 3.3900e+02 3.6500e+02 3.5800e+02
 3.2100e+02 5.4700e+02 3.7200e+02 4.2100e+02 2.8400e+02 2.9100e+02
 2.9200e+02 4.5100e+02 7.2100e+02 7.7700e+02 1.1170e+03 1.1970e+03
 1.0880e+03 3.7300e+02 3.2900e+02 3.6800e+02 4.5800e+02 8.0700e+02
 7.1600e+02 1.1590e+03 9.2000e+02 1.1300e+03 2.6500e+02 4.0300e+02
 5.5500e+02 5.4900e+02 5.1500e+02 8.6300e+02 5.8300e+02 6.5200e+02
 3.9000e+02 4.0500e+02 3.1800e+02 2.0700e+02 5.7000e+02 8.1500e+02
 8.8800e+02 5.9600e+02 6.8200e+02 8.1900e+02 3.3100e+02 1.3100e+02
 2.4200e+02 9.4000e+02 6.5400e+02 1.0410e+03 2.1000e+02 6.3600e+02
 5.3300e+02 9.1500e+02 5.0500e+02 2.3950e+03 2.1720e+03 1.4050e+03
 2.5750e+03 1.2720e+03 1.1250e+03 1.1560e+03 3.3600e+02 4.8400e+02
 6.6300e+02 9.5100e+02 5.5000e+02 2.1100e+02 1.7800e+02 7.5100e+02
 1.3300e+03 4.1000e+02 9.3000e+02 5.6900e+02 2.5310e+03 2.3260e+03
 1.4750e+03 3.8480e+03 2.2190e+03]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento"
})


# Uniformazione minuscolo per la colonna sesso e tipo_violenza e standardizzazione
df["sesso"] = df["sesso"].str.lower().str.strip()
df["tipo_violenza"] = df["tipo_violenza"].str.lower().str.strip()

df["tipo_violenza"] = df["tipo_violenza"].replace({
    "atti persecutori/ stalking": "atti persecutori/stalking"
})

# Rimozione delle voci aggregate "totale" e "tutte le voci"
# da sesso e tipo_violenza per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["tipo_violenza"] != "tutte le voci")
]


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

  territorio   sesso    tipo_violenza  periodo  numero_vittime
0     italia  maschi  violenza fisica     2015              67
1     italia  maschi  violenza fisica     2016              80
2     italia  maschi  violenza fisica     2017              66
3     italia  maschi  violenza fisica     2018              82
4     italia  maschi  violenza fisica     2019              62
5     italia  maschi  violenza fisica     2020             189
6     italia  maschi  violenza fisica     2021             158
7     italia  maschi  violenza fisica     2022              80
8     italia  maschi  violenza fisica     2023             146
9     italia  maschi  violenza fisica     2024             162

<class 'pandas.core.frame.DataFrame'>
Index: 3535 entries, 0 to 6572
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   territorio      3535 non-null   object
 1   sesso           3535 non-null   object
 2   tipo_violenza   3535 non-null   object
 3   periodo         3535 non-null   int64
 4   numero_vittime  3535 non-null   int64
dtypes: int64(2), object(3)
memory usage: 165.7+ KB

Missing values per colonna:

territorio        0
sesso             0
tipo_violenza     0
periodo           0
numero_vittime    0
dtype: int64

Numero valori unici per colonna:

numero_vittime    466
territorio         28
tipo_violenza      15
periodo            10
sesso               3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'bolzano' 'trento' 'veneto' 'friuli venezia giulia'
 'emilia romagna' 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud'
 'abruzzo' 'molise' 'campania' 'puglia' 'basilicata' 'calabria' 'isole'
 'sicilia' 'sardegna' 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: tipo_violenza
['violenza fisica' 'violenza sessuale' 'minacce' 'mobbing'
 'diffusione illecita di immagini o di video sessualmente espliciti'
 'violenza psicologica' 'violenza economica' 'atti persecutori/stalking'
 'violenza digitale' 'altro' 'non risponde' 'non disponibile' 'tratta'
 'sfruttamento della prostituzione' 'matrimonio forzato']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[  67   80   66   82   62  189  158  146  162   23   29   45   25   94
  116   42   24   14   19   13   12   26   32   21    5    8    3    1
    4    7  134  128  107  182  148   74  140  154    2    9   76   20
   10   11    6   27   38   18   44   64   28 3693 3727 3553 4166 3698
 7250 6949 5024 6662 7126  258  327  493  412  479 1040 1406  857  673
  598  281  325  337  362  311  482  755  610  119   15   59   40   22
   30 2784 2837 2732 3640 3263 5134 5240 3818 5267 6194  139  147  143
  122  113  180  125 1090 1513  141   96   68   47  199  155  153   78
  450  352  432  543  501  784  989 1004  344  251 1296 1017   17   33
   31   37  964 1080  952 1045  939 1741 1631 1264 1506 1904   89  118
  112  245  334  231  165  195   73   84   88   77  109  181  160   51
   16  785  846  778  932  887 1310 1223 1005 1317 1630   43   35  273
  446   34   85   72   69   71   65   41   50   39  295  332  283  296
  491  429  312  392  490   61   54   48   46  257  271  230  309  260
  351  350  299  374  399  102  105  142  101  115  164   86  110   87
  136  558  649  597  628  578 1104 1057  845  998 1241   49   55  216
  150  111  130   52  120  100  452  457  535  544  833  762  617  839
 1086  184  317  488  474  436  545  527  948 1036  771  974 1289   56
  240  144  114   53   57  106  525  461  719  789  607  822 1192  175
  330  238  223  274  530  494  619  179  159  247  328  370  278  366
  528   58   70   83  135  201  202  170  220  204  401  301  361  526
   90   36  169  151  219  187  323  357  276  326  467  137  802  775
  699  910  829 1534 1552 1216 1497 1653  188  177  124   81  152  661
  642  571  867  824 1068 1179  877 1058 1350  236   75   79  183  227
  208  416  290  353  455  225  304  252  380   92   99  145  121  472
  487  537  492  900  965  732  898  937   63  194   97  117   93  382
  404  473  483  621  670  662  745  927  860  797 1006 1502 1464 1039
 1361  218  126  615  757  700  959  782  810 1066  149  129   91   95
  462  437  395  519  386  693  685  552  631  287  209  319  409  465
  248  259  406  417  418  250  174  302  314  239  255  335  103  185
  132   60  108  339  365  322  358  321  529  547  372  421  468  284
  291  270  292  345  451  272  265  379  403  310  203  282  297  256
  123   98  127  331  940  654 1041  172  210  636  533  915  505  212
  678  722 1125  830]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/vittime.tipo_violenza.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/vittime.tipo_violenza.csv