In [1]:
import pandas as pd

df = pd.read_csv("../raw/Vittime.motivo_chiamata.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,PURPOSE_CALL,Motivi della chiamata,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2015.0,97.0,NaN,NaN
1,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2016.0,111.0,NaN,NaN
2,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2017.0,91.0,NaN,NaN
3,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2018.0,61.0,NaN,NaN
4,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2019.0,51.0,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 85
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,REPORT_VIOL,Segnalazione di un caso di violenza,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,ALL,Tutte le voci,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2015,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2017,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2018,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2019,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2020,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2022,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2023,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2024,21,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2016,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,REPORT_VIOL,Segnalazione di un caso di violenza,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,EMERGENCY,Emergenza,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,EMERGENCY,Emergenza,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2017,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2018,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2022,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,ALL,Tutte le voci,2024,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,REPORT_VIOL,Segnalazione di un caso di violenza,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,ALL,Tutte le voci,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2015,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2017,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_STALK_SEEK,Richiesta di aiuto vittima di stalking,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2015,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2016,5,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2017,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2018,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2019,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2020,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2022,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2023,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,VICT_VIOL_SEEK,Richiesta di aiuto vittima di violenza,2024,23,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2015,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2016,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2021,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,REPORT_VIOL,Segnalazione di un caso di violenza,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,EMERGENCY,Emergenza,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,EMERGENCY,Emergenza,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2017,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2018,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2022,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,ALL,Tutte le voci,2024,24,,']


============================================================
Colonna: Frequenza
Numero valori unici: 2
Valori unici:
['Annuale' nan]


============================================================
Colonna: REF_AREA
Numero valori unici: 29
Valori unici:
['IT' 'ITC' 'ITC1' nan 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 29
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' nan 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 2
Valori unici:
['VICTIMS' nan]


============================================================
Colonna: Indicatore
Numero valori unici: 2
Valori unici:
['Vittime di violenza' nan]


============================================================
Colonna: SEX
Numero valori unici: 5
Valori unici:
['M' 'F' 'NRP' 'T' nan]


============================================================
Colonna: Sesso
Numero valori unici: 5
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale' nan]


============================================================
Colonna: PURPOSE_CALL
Numero valori unici: 7
Valori unici:
['VICT_STALK_SEEK' 'VICT_VIOL_SEEK' 'VICT_DISCR_SEEK' 'REPORT_VIOL'
 'EMERGENCY' 'ALL' nan]


============================================================
Colonna: Motivi della chiamata
Numero valori unici: 7
Valori unici:
['Richiesta di aiuto vittima di stalking'
 'Richiesta di aiuto vittima di violenza'
 'Richiesta di aiuto per discriminazione'
 'Segnalazione di un caso di violenza' 'Emergenza' 'Tutte le voci' nan]


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 11
Valori unici:
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.   nan]


============================================================
Colonna: Osservazione
Numero valori unici: 942
Valori unici:
[9.7000e+01 1.1100e+02 9.1000e+01 6.1000e+01 5.1000e+01 1.1800e+02
 1.4000e+02 7.9000e+01 1.0800e+02 1.1900e+02 1.5400e+02 1.2200e+02
 1.3400e+02 1.4800e+02 1.2800e+02 3.4200e+02 3.1400e+02 2.4500e+02
 2.3400e+02 1.0000e+00 6.0000e+00 5.0000e+00 3.0000e+00 4.4000e+01
 5.5000e+01 5.0000e+01 4.2000e+01 2.7000e+01 1.0100e+02 8.0000e+01
 7.2000e+01 1.6000e+01 1.1000e+01 1.0000e+01 1.2000e+01 4.0000e+00
 2.0000e+00 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02
 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 9.2400e+02
 8.7500e+02 8.2700e+02 8.6500e+02 8.4600e+02 1.2240e+03 1.3720e+03
 1.0560e+03 1.3800e+03 1.8720e+03 5.1770e+03 5.3120e+03 5.3470e+03
 6.9060e+03 6.3550e+03 1.1310e+04 1.1481e+04 8.9930e+03 1.1013e+04
 1.2435e+04 1.5060e+03 1.5260e+03 1.4550e+03 1.3730e+03 1.0660e+03
 2.4720e+03 2.7990e+03 1.5650e+03 2.0620e+03 1.8100e+03 1.6300e+02
 1.1700e+02 1.7000e+02 1.9700e+02 1.6000e+02 6.2000e+01 1.7000e+01
 7.7700e+03 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04
 1.5720e+04 1.1632e+04 1.4455e+04 1.6117e+04 1.2400e+02 1.0480e+03
 8.2600e+02 1.6400e+02 9.0000e+01 9.0000e+00 1.5000e+01 8.3000e+01
 4.1000e+01 1.4030e+03 1.0810e+03 1.0210e+03 9.8600e+02 9.1800e+02
 9.2600e+02 8.9700e+02 1.3420e+03 1.5120e+03 1.1350e+03 1.5960e+03
 2.1150e+03 5.3310e+03 5.4340e+03 5.4810e+03 7.0540e+03 6.4830e+03
 1.1652e+04 1.1795e+04 9.1270e+03 1.2306e+04 1.3495e+04 1.5500e+03
 1.5810e+03 1.5050e+03 1.4150e+03 1.0930e+03 2.5730e+03 2.8790e+03
 1.6090e+03 2.2980e+03 1.9800e+03 1.8000e+02 1.2300e+02 1.8100e+02
 2.0700e+02 1.7400e+02 1.3200e+02 7.4000e+01 3.4000e+01 8.0820e+03
 8.1250e+03 8.0850e+03 9.6020e+03 8.6470e+03 1.5708e+04 1.6272e+04
 1.1909e+04 1.6283e+04 1.7631e+04 3.2000e+01 2.8000e+01 2.0000e+01
 2.6000e+01 2.2000e+01 2.9000e+01 3.8000e+01 5.8000e+01 5.9000e+01
 2.5000e+01 4.6000e+01 8.0000e+00 1.8000e+01 2.4000e+01 6.4000e+01
 7.1000e+01 5.6000e+01 1.0200e+02 1.0300e+02 9.6000e+01 2.6300e+02
 2.2200e+02 2.0800e+02 2.4200e+02 2.1200e+02 2.9600e+02 2.9700e+02
 2.5800e+02 3.3000e+02 5.3400e+02 1.3570e+03 1.4730e+03 1.3950e+03
 1.6890e+03 1.6160e+03 2.6300e+03 2.6120e+03 2.1350e+03 2.5360e+03
 3.3220e+03 4.1000e+02 5.0600e+02 4.3600e+02 3.5100e+02 2.9900e+02
 6.1600e+02 6.0600e+02 3.9700e+02 5.1800e+02 4.7900e+02 4.7000e+01
 3.6000e+01 3.0000e+01 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 7.0000e+01 2.5000e+02 2.2500e+02 2.2400e+02 3.1600e+02 3.2300e+02
 2.7300e+02 3.5700e+02 5.6800e+02 1.3860e+03 1.4990e+03 1.4330e+03
 1.7180e+03 1.6500e+03 2.6880e+03 2.6710e+03 2.1600e+03 2.6220e+03
 3.4000e+03 4.2000e+02 5.1600e+02 4.4800e+02 3.6600e+02 3.0700e+02
 6.3800e+02 6.2400e+02 4.0600e+02 5.6000e+02 4.9800e+02 4.8000e+01
 4.0000e+01 3.9000e+01 3.1000e+01 2.1490e+03 2.2770e+03 2.1460e+03
 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03 2.8450e+03 3.5500e+03
 4.4750e+03 1.3000e+01 1.4000e+01 1.9000e+01 5.2000e+01 6.5000e+01
 7.7000e+01 1.2000e+02 4.1800e+02 4.8200e+02 4.2700e+02 5.2100e+02
 4.9300e+02 7.3500e+02 7.2500e+02 5.8700e+02 6.9700e+02 8.1700e+02
 1.4300e+02 1.0900e+02 8.5000e+01 1.6200e+02 1.4900e+02 8.9000e+01
 1.3500e+02 1.3900e+02 6.4500e+02 6.8400e+02 6.2300e+02 7.0900e+02
 6.3200e+02 9.8500e+02 9.5200e+02 7.4700e+02 9.1100e+02 1.0760e+03
 9.2000e+01 5.4000e+01 6.6000e+01 7.3000e+01 8.4000e+01 1.3000e+02
 4.3100e+02 4.9200e+02 4.4700e+02 5.3000e+02 5.0300e+02 7.4900e+02
 7.5000e+02 5.9200e+02 7.1800e+02 8.3800e+02 1.4600e+02 1.3700e+02
 8.7000e+01 1.6700e+02 1.5500e+02 9.3000e+01 1.4400e+02 6.6900e+02
 7.0300e+02 6.5100e+02 7.2200e+02 6.4700e+02 1.0110e+03 9.8800e+02
 7.5900e+02 9.4800e+02 1.1120e+03        nan 7.0000e+00 2.1000e+01
 2.3000e+01 1.4100e+02 1.3800e+02 1.2900e+02 1.7500e+02 2.2700e+02
 2.3300e+02 1.9900e+02 2.8400e+02 3.7000e+01 3.5000e+01 2.0500e+02
 2.0900e+02 1.8300e+02 2.2800e+02 1.8400e+02 3.1000e+02 2.3100e+02
 3.6000e+02 1.7800e+02 2.4000e+02 2.3800e+02 2.9300e+02 2.1500e+02
 1.8800e+02 1.8900e+02 3.2200e+02 3.1900e+02 2.3500e+02 2.7700e+02
 3.7000e+02 3.3000e+01 6.9000e+01 1.5800e+02 1.4700e+02 1.5200e+02
 1.9200e+02 1.8700e+02 3.7200e+02 7.9100e+02 8.4800e+02 8.3300e+02
 9.7600e+02 1.6540e+03 1.3560e+03 1.6360e+03 2.2000e+03 3.0600e+02
 2.6400e+02 2.1300e+02 4.0100e+02 4.1500e+02 2.8000e+02 3.4100e+02
 3.0500e+02 1.2150e+03 1.3090e+03 1.2600e+03 1.3740e+03 1.3340e+03
 2.2630e+03 2.2640e+03 1.8020e+03 2.2040e+03 2.8770e+03 4.5000e+01
 1.7600e+02 1.6600e+02 1.5000e+02 1.6500e+02 1.5300e+02 2.0400e+02
 2.4800e+02 3.9500e+02 8.0500e+02 8.6200e+02 8.5000e+02 1.0030e+03
 9.9700e+02 1.6850e+03 1.6790e+03 1.6950e+03 2.2460e+03 3.1200e+02
 2.7200e+02 1.9300e+02 4.2600e+02 3.6900e+02 1.2560e+03 1.3480e+03
 1.2970e+03 1.3700e+03 2.3240e+03 2.3220e+03 1.8350e+03 2.3180e+03
 2.9690e+03 4.3000e+01 4.9000e+01 7.8000e+01 6.0000e+01 1.0700e+02
 1.5700e+02 3.8600e+02 6.8700e+02 6.9200e+02 6.7800e+02 9.4300e+02
 9.1200e+02 1.5290e+03 1.3500e+03 1.6340e+03 2.3250e+03 1.7900e+02
 3.0800e+02 4.0000e+02 1.9500e+02 3.0100e+02 1.0260e+03 1.0090e+03
 9.7500e+02 1.2550e+03 1.1960e+03 2.0050e+03 2.2780e+03 1.7020e+03
 2.1750e+03 3.0120e+03 1.1000e+02 1.1600e+02 1.1500e+02 2.4300e+02
 2.4400e+02 4.0300e+02 7.1100e+02 7.1000e+02 9.6300e+02 9.2900e+02
 1.5720e+03 1.6780e+03 1.3640e+03 1.6870e+03 2.3910e+03 2.0000e+02

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",         
    "SEX",                
    "PURPOSE_CALL",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (3928, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Motivi della chiamata', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Motivi della chiamata": "motivo_chiamata",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: motivo_chiamata
['Richiesta di aiuto vittima di stalking'
 'Richiesta di aiuto vittima di violenza'
 'Richiesta di aiuto per discriminazione'
 'Segnalazione di un caso di violenza' 'Emergenza' 'Tutte le voci']

Colonna: periodo
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.]

Colonna: numero_vittime
[9.7000e+01 1.1100e+02 9.1000e+01 6.1000e+01 5.1000e+01 1.1800e+02
 1.4000e+02 7.9000e+01 1.0800e+02 1.1900e+02 1.5400e+02 1.2200e+02
 1.3400e+02 1.4800e+02 1.2800e+02 3.4200e+02 3.1400e+02 2.4500e+02
 2.3400e+02 1.0000e+00 6.0000e+00 5.0000e+00 3.0000e+00 4.4000e+01
 5.5000e+01 5.0000e+01 4.2000e+01 2.7000e+01 1.0100e+02 8.0000e+01
 7.2000e+01 1.6000e+01 1.1000e+01 1.0000e+01 1.2000e+01 4.0000e+00
 2.0000e+00 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02
 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 9.2400e+02
 8.7500e+02 8.2700e+02 8.6500e+02 8.4600e+02 1.2240e+03 1.3720e+03
 1.0560e+03 1.3800e+03 1.8720e+03 5.1770e+03 5.3120e+03 5.3470e+03
 6.9060e+03 6.3550e+03 1.1310e+04 1.1481e+04 8.9930e+03 1.1013e+04
 1.2435e+04 1.5060e+03 1.5260e+03 1.4550e+03 1.3730e+03 1.0660e+03
 2.4720e+03 2.7990e+03 1.5650e+03 2.0620e+03 1.8100e+03 1.6300e+02
 1.1700e+02 1.7000e+02 1.9700e+02 1.6000e+02 6.2000e+01 1.7000e+01
 7.7700e+03 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04
 1.5720e+04 1.1632e+04 1.4455e+04 1.6117e+04 1.2400e+02 1.0480e+03
 8.2600e+02 1.6400e+02 9.0000e+01 9.0000e+00 1.5000e+01 8.3000e+01
 4.1000e+01 1.4030e+03 1.0810e+03 1.0210e+03 9.8600e+02 9.1800e+02
 9.2600e+02 8.9700e+02 1.3420e+03 1.5120e+03 1.1350e+03 1.5960e+03
 2.1150e+03 5.3310e+03 5.4340e+03 5.4810e+03 7.0540e+03 6.4830e+03
 1.1652e+04 1.1795e+04 9.1270e+03 1.2306e+04 1.3495e+04 1.5500e+03
 1.5810e+03 1.5050e+03 1.4150e+03 1.0930e+03 2.5730e+03 2.8790e+03
 1.6090e+03 2.2980e+03 1.9800e+03 1.8000e+02 1.2300e+02 1.8100e+02
 2.0700e+02 1.7400e+02 1.3200e+02 7.4000e+01 3.4000e+01 8.0820e+03
 8.1250e+03 8.0850e+03 9.6020e+03 8.6470e+03 1.5708e+04 1.6272e+04
 1.1909e+04 1.6283e+04 1.7631e+04 3.2000e+01 2.8000e+01 2.0000e+01
 2.6000e+01 2.2000e+01 2.9000e+01 3.8000e+01 5.8000e+01 5.9000e+01
 2.5000e+01 4.6000e+01 8.0000e+00 1.8000e+01 2.4000e+01 6.4000e+01
 7.1000e+01 5.6000e+01 1.0200e+02 1.0300e+02 9.6000e+01 2.6300e+02
 2.2200e+02 2.0800e+02 2.4200e+02 2.1200e+02 2.9600e+02 2.9700e+02
 2.5800e+02 3.3000e+02 5.3400e+02 1.3570e+03 1.4730e+03 1.3950e+03
 1.6890e+03 1.6160e+03 2.6300e+03 2.6120e+03 2.1350e+03 2.5360e+03
 3.3220e+03 4.1000e+02 5.0600e+02 4.3600e+02 3.5100e+02 2.9900e+02
 6.1600e+02 6.0600e+02 3.9700e+02 5.1800e+02 4.7900e+02 4.7000e+01
 3.6000e+01 3.0000e+01 2.0770e+03 2.2130e+03 2.0750e+03 2.3200e+03
 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03 3.3840e+03 4.3350e+03
 7.0000e+01 2.5000e+02 2.2500e+02 2.2400e+02 3.1600e+02 3.2300e+02
 2.7300e+02 3.5700e+02 5.6800e+02 1.3860e+03 1.4990e+03 1.4330e+03
 1.7180e+03 1.6500e+03 2.6880e+03 2.6710e+03 2.1600e+03 2.6220e+03
 3.4000e+03 4.2000e+02 5.1600e+02 4.4800e+02 3.6600e+02 3.0700e+02
 6.3800e+02 6.2400e+02 4.0600e+02 5.6000e+02 4.9800e+02 4.8000e+01
 4.0000e+01 3.9000e+01 3.1000e+01 2.1490e+03 2.2770e+03 2.1460e+03
 2.3810e+03 2.2150e+03 3.6740e+03 3.6350e+03 2.8450e+03 3.5500e+03
 4.4750e+03 1.3000e+01 1.4000e+01 1.9000e+01 5.2000e+01 6.5000e+01
 7.7000e+01 1.2000e+02 4.1800e+02 4.8200e+02 4.2700e+02 5.2100e+02
 4.9300e+02 7.3500e+02 7.2500e+02 5.8700e+02 6.9700e+02 8.1700e+02
 1.4300e+02 1.0900e+02 8.5000e+01 1.6200e+02 1.4900e+02 8.9000e+01
 1.3500e+02 1.3900e+02 6.4500e+02 6.8400e+02 6.2300e+02 7.0900e+02
 6.3200e+02 9.8500e+02 9.5200e+02 7.4700e+02 9.1100e+02 1.0760e+03
 9.2000e+01 5.4000e+01 6.6000e+01 7.3000e+01 8.4000e+01 1.3000e+02
 4.3100e+02 4.9200e+02 4.4700e+02 5.3000e+02 5.0300e+02 7.4900e+02
 7.5000e+02 5.9200e+02 7.1800e+02 8.3800e+02 1.4600e+02 1.3700e+02
 8.7000e+01 1.6700e+02 1.5500e+02 9.3000e+01 1.4400e+02 6.6900e+02
 7.0300e+02 6.5100e+02 7.2200e+02 6.4700e+02 1.0110e+03 9.8800e+02
 7.5900e+02 9.4800e+02 1.1120e+03 7.0000e+00 2.1000e+01 2.3000e+01
 1.4100e+02 1.3800e+02 1.2900e+02 1.7500e+02 2.2700e+02 2.3300e+02
 1.9900e+02 2.8400e+02 3.7000e+01 3.5000e+01 2.0500e+02 2.0900e+02
 1.8300e+02 2.2800e+02 1.8400e+02 3.1000e+02 2.3100e+02 3.6000e+02
 1.7800e+02 2.4000e+02 2.3800e+02 2.9300e+02 2.1500e+02 1.8800e+02
 1.8900e+02 3.2200e+02 3.1900e+02 2.3500e+02 2.7700e+02 3.7000e+02
 3.3000e+01 6.9000e+01 1.5800e+02 1.4700e+02 1.5200e+02 1.9200e+02
 1.8700e+02 3.7200e+02 7.9100e+02 8.4800e+02 8.3300e+02 9.7600e+02
 1.6540e+03 1.3560e+03 1.6360e+03 2.2000e+03 3.0600e+02 2.6400e+02
 2.1300e+02 4.0100e+02 4.1500e+02 2.8000e+02 3.4100e+02 3.0500e+02
 1.2150e+03 1.3090e+03 1.2600e+03 1.3740e+03 1.3340e+03 2.2630e+03
 2.2640e+03 1.8020e+03 2.2040e+03 2.8770e+03 4.5000e+01 1.7600e+02
 1.6600e+02 1.5000e+02 1.6500e+02 1.5300e+02 2.0400e+02 2.4800e+02
 3.9500e+02 8.0500e+02 8.6200e+02 8.5000e+02 1.0030e+03 9.9700e+02
 1.6850e+03 1.6790e+03 1.6950e+03 2.2460e+03 3.1200e+02 2.7200e+02
 1.9300e+02 4.2600e+02 3.6900e+02 1.2560e+03 1.3480e+03 1.2970e+03
 1.3700e+03 2.3240e+03 2.3220e+03 1.8350e+03 2.3180e+03 2.9690e+03
 4.3000e+01 4.9000e+01 7.8000e+01 6.0000e+01 1.0700e+02 1.5700e+02
 3.8600e+02 6.8700e+02 6.9200e+02 6.7800e+02 9.4300e+02 9.1200e+02
 1.5290e+03 1.3500e+03 1.6340e+03 2.3250e+03 1.7900e+02 3.0800e+02
 4.0000e+02 1.9500e+02 3.0100e+02 1.0260e+03 1.0090e+03 9.7500e+02
 1.2550e+03 1.1960e+03 2.0050e+03 2.2780e+03 1.7020e+03 2.1750e+03
 3.0120e+03 1.1000e+02 1.1600e+02 1.1500e+02 2.4300e+02 2.4400e+02
 4.0300e+02 7.1100e+02 7.1000e+02 9.6300e+02 9.2900e+02 1.5720e+03
 1.6780e+03 1.3640e+03 1.6870e+03 2.3910e+03 2.0000e+02 1.9100e+02
 4.0700e+02 3.2700e+02 3.1300e+02 1.0750e+03 1.2860e+03 1.2280e+03
 2.0830e+03 2.3390e+03 1.7310e+03 2.2710e+03 3.1140e+03 1.0400e+02
 1.0600e+02 1.1200e+02 8.6000e+01 5.7000e+01 7.6000e+01 1.1300e+02
 7.5000e+01 6.7000e+01 9.4000e+01 8.2000e+01 1.6100e+02 3.2500e+02
 4.5700e+02 4.7000e+02 7.3800e+02 8.3000e+02 6.8800e+02 7.7300e+02
 1.0920e+03 9.8000e+01 9.9000e+01 4.8000e+02 4.6800e+02 4.7500e+02
 6.1400e+02 6.1100e+02 9.5600e+02 1.1410e+03 8.6100e+02 1.0140e+03
 1.3930e+03 1.0500e+02 1.6800e+02 3.3300e+02 3.3100e+02 4.7800e+02
 7.5600e+02 8.3900e+02 6.9600e+02 7.9900e+02 1.1190e+03 1.4500e+02
 5.0400e+02 4.8600e+02 4.9000e+02 6.2600e+02 9.9200e+02 1.1690e+03
 8.7100e+02 1.4360e+03 1.0000e+02 1.2600e+02 1.6900e+02 8.1000e+01
 1.3300e+02 1.7100e+02 1.7300e+02 2.6900e+02 9.5000e+01 2.7400e+02
 3.4900e+02 6.6300e+02 7.0100e+02 5.5800e+02 6.2700e+02 9.3100e+02
 1.3100e+02 1.1400e+02 4.3700e+02 4.2300e+02 3.9400e+02 5.1300e+02
 8.8200e+02 9.6500e+02 8.5300e+02 1.2080e+03 3.0300e+02 3.9200e+02
 3.5400e+02 6.8100e+02 7.1700e+02 5.6300e+02 6.4900e+02 9.6100e+02
 1.2100e+02 4.5600e+02 4.4300e+02 4.1300e+02 5.2200e+02 4.9100e+02
 9.1300e+02 9.9400e+02 7.2700e+02 8.9400e+02 6.3000e+01 2.1100e+02
 2.1000e+02 1.8500e+02 1.9800e+02 2.3200e+02 2.4100e+02 3.3400e+02
 2.9400e+02 1.1430e+03 1.1160e+03 1.0790e+03 1.4290e+03 2.2830e+03
 2.4900e+03 1.9670e+03 2.2920e+03 2.8020e+03 3.3500e+02 2.5700e+02
 5.0200e+02 5.4500e+02 3.5800e+02 4.7600e+02 3.6100e+02 1.7150e+03
 1.5700e+03 2.0960e+03 1.9410e+03 3.0530e+03 3.3850e+03 3.0620e+03
 3.5730e+03 2.3700e+02 2.4700e+02 2.7000e+02 3.1500e+02 4.4500e+02
 1.1710e+03 1.1480e+03 1.1090e+03 1.5820e+03 1.4580e+03 2.3630e+03
 2.5450e+03 1.9970e+03 2.3760e+03 2.8910e+03 3.4700e+02 3.4400e+02
 3.1700e+02 3.7800e+02 1.7710e+03 1.7540e+03 1.6330e+03 2.1530e+03
 1.9890e+03 3.1830e+03 3.4870e+03 2.6430e+03 3.2130e+03 3.7240e+03
 2.5100e+02 2.8500e+02 4.0800e+02 3.7500e+02 6.0700e+02 5.8800e+02
 4.6700e+02 5.5600e+02 7.7100e+02 3.7900e+02 5.5900e+02 8.2900e+02
 7.2400e+02 9.9500e+02 2.5900e+02 2.2100e+02 4.1900e+02 3.7600e+02
 6.3400e+02 6.0400e+02 5.7500e+02 7.9400e+02 1.5900e+02 3.8900e+02
 4.5000e+02 5.7300e+02 5.1900e+02 8.6900e+02 8.5800e+02 1.0340e+03
 1.7200e+02 1.4200e+02 1.9600e+02 8.8000e+01 1.2500e+02 2.2000e+02
 2.5600e+02 2.8100e+02 2.0300e+02 2.2600e+02 3.4300e+02 2.6700e+02
 1.3600e+02 2.1400e+02 2.9000e+02 2.3000e+02 3.5300e+02 2.7900e+02
 6.9500e+02 8.8900e+02 8.3700e+02 1.3400e+03 1.5250e+03 1.1650e+03
 1.3830e+03 1.5780e+03 1.9000e+02 2.8700e+02 2.2300e+02 1.0580e+03
 8.7200e+02 1.1950e+03 1.1450e+03 1.7970e+03 2.0440e+03 1.5520e+03
 1.8750e+03 5.3000e+01 2.5400e+02 6.8500e+02 7.1200e+02 6.2100e+02
 9.0600e+02 1.3840e+03 1.5610e+03 1.1790e+03 1.4370e+03 1.6290e+03
 2.9800e+02 3.3900e+02 3.2400e+02 1.0450e+03 1.1010e+03 9.0500e+02
 1.2320e+03 1.1820e+03 1.8690e+03 2.1040e+03 1.5870e+03 1.9750e+03
 2.0920e+03 1.8600e+02 1.5100e+02 1.7700e+02 2.0100e+02 1.9400e+02
 2.9100e+02 1.1810e+03 1.1890e+03 1.5210e+03 2.1660e+03 2.2510e+03
 1.7390e+03 1.8870e+03 3.5600e+02 3.0000e+02 5.0800e+02 2.5300e+02
 1.7100e+03 1.5410e+03 2.0370e+03 1.8060e+03 2.8820e+03 3.0050e+03
 2.1960e+03 2.3770e+03 2.8370e+03 2.4900e+02 2.1600e+02 3.0900e+02
 1.2250e+03 1.2160e+03 1.4050e+03 2.2240e+03 2.3110e+03 1.7580e+03
 1.9480e+03 2.3430e+03 3.6300e+02 2.7800e+02 4.6200e+02 5.1500e+02
 1.8830e+03 1.7760e+03 1.5930e+03 2.0990e+03 1.8490e+03 2.9640e+03
 3.0890e+03 2.2340e+03 2.4810e+03 2.2900e+02 2.1700e+02 2.8900e+02
 2.1900e+02 2.3900e+02 2.8200e+02 2.7500e+02 5.7400e+02 5.9300e+02
 5.1400e+02 7.3600e+02 6.6100e+02 9.7800e+02 7.6900e+02 1.0390e+03
 1.2700e+02 8.7400e+02 9.6000e+02 8.4500e+02 1.2950e+03 9.6800e+02
 1.0330e+03 1.2870e+03 5.8600e+02 6.0300e+02 5.2000e+02 6.7200e+02
 9.9600e+02 7.8100e+02 9.0400e+02 7.4500e+02 9.9000e+02 8.6400e+02
 1.3230e+03 1.4070e+03 9.9100e+02 1.0830e+03 1.3450e+03 3.0200e+02
 2.8800e+02 6.5400e+02 5.2500e+02 7.0200e+02 4.9500e+02 4.1400e+02
 5.9000e+02 4.6400e+02 8.2000e+02 8.7900e+02 6.3500e+02 3.2900e+02
 4.4100e+02 6.1200e+02 6.7100e+02 4.9600e+02 5.4100e+02 7.3200e+02
 4.2800e+02 8.5200e+02 9.0200e+02 6.4200e+02 7.0600e+02 2.6600e+02
 2.5500e+02 2.0200e+02 3.5900e+02 3.4000e+02 5.3500e+02 6.1300e+02
 8.5600e+02 9.2000e+02 6.4600e+02 6.8600e+02 6.8000e+01 7.2100e+02
 7.7700e+02 7.8400e+02 7.0000e+02 1.1170e+03 1.1970e+03 1.0880e+03
 5.1000e+02 5.4600e+02 8.8100e+02 9.4100e+02 7.0700e+02 8.7700e+02
 8.0200e+02 7.4000e+02 8.0700e+02 7.1600e+02 1.1590e+03 1.1300e+03
 3.4500e+02 3.6400e+02 3.8000e+02 4.3500e+02 4.3000e+02 6.7300e+02
 4.6100e+02 5.5500e+02 5.4900e+02 7.8600e+02 8.6300e+02 5.8300e+02
 6.5200e+02 7.8500e+02 3.5500e+02 3.8700e+02 4.3900e+02 6.2900e+02
 5.2900e+02 6.3900e+02 5.7000e+02 5.6500e+02 8.1500e+02 8.8800e+02
 5.9600e+02 6.8200e+02 8.1900e+02 1.5600e+02 1.8200e+02 2.5200e+02
 2.6500e+02 3.9000e+02 1.7620e+03 1.4490e+03 1.0710e+03 1.9780e+03
 4.1200e+02 5.2700e+02 3.7300e+02 3.8800e+02 8.8700e+02 7.7800e+02
 5.4400e+02 2.3950e+03 2.1720e+03 2.5750e+03 1.2720e+03 9.1500e+02
 6.6200e+02 1.1560e+03 5.7800e+02 5.5200e+02 1.8340e+03 1.1060e+03
 2.9660e+03 5.5400e+02 4.7400e+02 4.0200e+02 9.3000e+02 5.6900e+02
 2.5310e+03 2.3260e+03 1.4750e+03 3.8480e+03 2.2190e+03]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento"
})


# Uniformazione minuscolo per la colonna sesso e motivo_chiamata
df["sesso"] = df["sesso"].str.lower().str.strip()
df["motivo_chiamata"] = df["motivo_chiamata"].str.lower().str.strip()


# Rimozione delle voci aggregate "totale" e "tutte le voci"
# da sesso e motivo_chiamata per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["motivo_chiamata"] != "tutte le voci")
]


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)



# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,territorio,sesso,motivo_chiamata,periodo,numero_vittime
0,italia,maschi,richiesta di aiuto vittima di stalking,2015,97
1,italia,maschi,richiesta di aiuto vittima di stalking,2016,111
2,italia,maschi,richiesta di aiuto vittima di stalking,2017,91
3,italia,maschi,richiesta di aiuto vittima di stalking,2018,61
4,italia,maschi,richiesta di aiuto vittima di stalking,2019,51
5,italia,maschi,richiesta di aiuto vittima di stalking,2020,118
6,italia,maschi,richiesta di aiuto vittima di stalking,2021,140
7,italia,maschi,richiesta di aiuto vittima di stalking,2022,79
8,italia,maschi,richiesta di aiuto vittima di stalking,2023,108
9,italia,maschi,richiesta di aiuto vittima di stalking,2024,119

<class 'pandas.core.frame.DataFrame'>
Index: 1930 entries, 0 to 3868
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   territorio       1930 non-null   object
 1   sesso            1930 non-null   object
 2   motivo_chiamata  1930 non-null   object
 3   periodo          1930 non-null   int64
 4   numero_vittime   1930 non-null   int64
dtypes: int64(2), object(3)
memory usage: 90.5+ KB

Missing values per colonna:

territorio         0
sesso              0
motivo_chiamata    0
periodo            0
numero_vittime     0
dtype: int64

Numero valori unici per colonna:

numero_vittime     432
territorio          28
periodo             10
motivo_chiamata      5
sesso                3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'bolzano' 'trento' 'veneto' 'friuli venezia giulia'
 'emilia romagna' 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud'
 'abruzzo' 'molise' 'campania' 'puglia' 'basilicata' 'calabria' 'isole'
 'sicilia' 'sardegna' 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: motivo_chiamata
['richiesta di aiuto vittima di stalking'
 'richiesta di aiuto vittima di violenza'
 'richiesta di aiuto per discriminazione'
 'segnalazione di un caso di violenza' 'emergenza']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[   97   111    91    61    51   118   140    79   108   119   154   122
   134   148   128   342   314   245   234     1     6     5     3    44
    55    50    42    27   101    80    72    16    11    10    12     4
     2   924   875   827   865   846  1224  1372  1056  1380  1872  5177
  5312  5347  6906  6355 11310 11481  8993 11013 12435  1506  1526  1455
  1373  1066  2472  2799  1565  2062  1810   163   117   170   197   160
    62    17   124  1048   826   164    90     9    15    83    41    32
    28    20    26    22    29    38    34    58    59    25    46     8
    18    24   263   222   208   242   212   296   297   258   330   534
  1357  1473  1395  1689  1616  2630  2612  2135  2536  3322   410   506
   436   351   299   616   606   397   518   479    47    36    30    13
    14    52    65    48    77    74    71   120   418   482   427   521
   493   735   725   587   697   817   143   109    85   162   149    89
   135   139     7    21    23   141   138   129   175   227   233   181
   199   284    37    40    35    19    31   158   147   152   144   192
   187   372   791   848   833   986   976  1654  1650  1356  1636  2200
   240   306   264   213   188   401   415   280   341   305    43    39
    93   102   107   218   157   386   687   692   678   943   912  1529
  1350  1634  2325   228   193   184   179   308   400   195   319   301
   104    86    57    56    54   161   322   325   457   470   738   830
   688   773  1092   112    94    98    78   153    99   100   126   103
   130    45    92    95   293   274   349   663   701   558   627   931
    70    76   131   166   114   211   210   185   198   232   241   334
   294  1143  1116  1079  1550  1429  2283  2490  1967  2292  2802   335
   327   307   257   502   545   358   476   361    73    63    69   115
   251   285   408   375   607   588   467   556   771    66    75   121
   172   167   256   281   132   116   133   235   669   695   889   837
  1340  1525  1165  1383  1578   190   287   223    60   231   186   151
   177   237   201   194   291  1181  1189  1521  2166  2251  1739  1887
   356   300   269   209   450   508   253   295    33   110   229    49
    81    84   113   574   593   514   736   661   978  1034   769  1039
   171   123   127   302   288   426   654   525   702    87   105   278
   243   495   515   535   613   573   856   920   646   686   853    68
   173   125   345   364   380   435   430   612   673   461   513   621
   150   155   178   244   247   204   279   286   560   541   390  1762
  1449  1071  1978   882   182   136   412   527   219   333   915   662]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/vittime.motivo_chiamata.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/vittime.motivo_chiamata.csv