In [1]:
import pandas as pd

df = pd.read_csv("../raw/Vittime.età.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,AGE,Età,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2015.0,3.0,NaN,NaN
1,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2016.0,2.0,NaN,NaN
2,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2017.0,3.0,NaN,NaN
3,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2020.0,3.0,NaN,NaN
4,A,Annuale,IT,Italia,VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2021.0,19.0,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 131
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,NSP,Non indicato,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,Y18-24,18-24 anni,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,Y45-54,45-54 anni,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,Y45-54,45-54 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,Y_GE65,65 anni e più,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,TOTAL,Totale,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,TOTAL,Totale,2018,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,TOTAL,Totale,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,TOTAL,Totale,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,M,Maschi,UNAV,Non disponibile,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NSP,Non indicato,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,NSP,Non indicato,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y18-24,18-24 anni,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y18-24,18-24 anni,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y18-24,18-24 anni,2022,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y18-24,18-24 anni,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y18-24,18-24 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2019,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y25-34,25-34 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2017,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2019,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2021,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y35-44,35-44 anni,2024,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2022,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y45-54,45-54 anni,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y55-64,55-64 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y55-64,55-64 anni,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y55-64,55-64 anni,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y55-64,55-64 anni,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y55-64,55-64 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,Y_GE65,65 anni e più,2024,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2017,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2018,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2022,14,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2023,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,TOTAL,Totale,2024,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2020,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,F,Femmine,UNAV,Non disponibile,2024,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,TOTAL,Totale,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,NRP,Non indicato,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NSP,Non indicato,2022,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,NSP,Non indicato,2024,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y18-24,18-24 anni,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y18-24,18-24 anni,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y18-24,18-24 anni,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y18-24,18-24 anni,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y18-24,18-24 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2019,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y25-34,25-34 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2017,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2019,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2021,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y35-44,35-44 anni,2024,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2018,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2022,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y45-54,45-54 anni,2024,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y55-64,55-64 anni,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y55-64,55-64 anni,2020,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y55-64,55-64 anni,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y55-64,55-64 anni,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y55-64,55-64 anni,2024,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2015,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2016,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2018,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2020,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2022,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2023,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,Y_GE65,65 anni e più,2024,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2015,12,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2016,11,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2017,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2018,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2019,9,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2020,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2021,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2022,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2023,7,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,TOTAL,Totale,2024,24,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2020,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2021,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2023,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',VICTIMS,Vittime di violenza,T,Totale,UNAV,Non disponibile,2024,8,,']


============================================================
Colonna: Frequenza
Numero valori unici: 2
Valori unici:
['Annuale' nan]


============================================================
Colonna: REF_AREA
Numero valori unici: 29
Valori unici:
['IT' 'ITC' 'ITC1' nan 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD1' 'ITD2' 'ITD3'
 'ITD4' 'ITD5' 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2'
 'ITF3' 'ITF4' 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 29
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' nan 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 2
Valori unici:
['VICTIMS' nan]


============================================================
Colonna: Indicatore
Numero valori unici: 2
Valori unici:
['Vittime di violenza' nan]


============================================================
Colonna: SEX
Numero valori unici: 5
Valori unici:
['M' 'F' 'NRP' 'T' nan]


============================================================
Colonna: Sesso
Numero valori unici: 5
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale' nan]


============================================================
Colonna: AGE
Numero valori unici: 11
Valori unici:
['NSP' 'Y_UN17' 'Y18-24' 'Y25-34' 'Y35-44' 'Y45-54' 'Y55-64' 'Y_GE65'
 'TOTAL' 'UNAV' nan]


============================================================
Colonna: Età
Numero valori unici: 11
Valori unici:
['Non indicato' 'Fino a 17 anni' '18-24 anni' '25-34 anni' '35-44 anni'
 '45-54 anni' '55-64 anni' '65 anni e più' 'Totale' 'Non disponibile' nan]


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 11
Valori unici:
[2015. 2016. 2017. 2020. 2021. 2022. 2023. 2024. 2018. 2019.   nan]


============================================================
Colonna: Osservazione
Numero valori unici: 931
Valori unici:
[3.0000e+00 2.0000e+00 1.9000e+01 2.0000e+01 5.2000e+01 4.0000e+00
 5.0000e+00 6.0000e+00 2.6000e+01 3.4000e+01 1.7000e+01 1.6000e+01
 1.2000e+01 1.8000e+01 2.4000e+01 4.9000e+01 5.0000e+01 3.0000e+01
 4.7000e+01 2.8000e+01 4.2000e+01 4.8000e+01 5.6000e+01 2.9000e+01
 7.0000e+01 5.4000e+01 4.0000e+01 7.9000e+01 4.5000e+01 6.0000e+01
 7.6000e+01 6.6000e+01 5.1000e+01 8.2000e+01 4.1000e+01 6.8000e+01
 7.8000e+01 5.9000e+01 3.8000e+01 6.9000e+01 4.3000e+01 3.1000e+01
 2.5000e+01 3.3000e+01 2.3000e+01 1.0000e+01 3.7000e+01 3.5000e+01
 3.6000e+01 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02
 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 4.4000e+01
 2.7000e+01 1.8900e+02 2.2400e+02 1.6000e+02 6.1000e+01 9.0000e+00
 8.8000e+01 4.1800e+02 4.7900e+02 1.2590e+03 7.8100e+02 8.7000e+01
 9.3000e+01 2.4200e+02 3.8800e+02 2.3200e+02 3.1400e+02 2.7200e+02
 4.9600e+02 4.8600e+02 5.0000e+02 5.8900e+02 6.7200e+02 1.0720e+03
 1.2970e+03 1.1230e+03 1.4190e+03 1.1170e+03 1.4020e+03 1.3840e+03
 1.3450e+03 1.5050e+03 1.6060e+03 2.1000e+03 2.0340e+03 1.8320e+03
 2.5060e+03 2.0140e+03 2.0650e+03 1.9720e+03 2.2360e+03 2.1780e+03
 2.7580e+03 2.4250e+03 2.3810e+03 3.0420e+03 2.4750e+03 1.6190e+03
 1.7310e+03 1.5630e+03 2.1190e+03 1.7670e+03 2.3500e+03 2.2870e+03
 2.0740e+03 2.5400e+03 2.2090e+03 8.9100e+02 8.8800e+02 8.1100e+02
 1.0060e+03 8.5900e+02 1.3250e+03 1.2910e+03 1.0740e+03 9.6200e+02
 8.2000e+02 6.8700e+02 7.1400e+02 6.3900e+02 7.6800e+02 6.1100e+02
 1.2500e+03 1.3330e+03 8.9500e+02 1.4310e+03 1.2690e+03 7.7700e+03
 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04
 1.1632e+04 1.4455e+04 1.6117e+04 5.4900e+02 4.5000e+02 8.2300e+02
 9.9100e+02 6.3200e+02 3.9430e+03 4.2470e+03 1.5420e+03 9.8200e+02

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",          
    "Indicatore",         
    "SEX",                
    "AGE",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (7341, 5)
Colonne rimanenti: ['Territorio', 'Sesso', 'Età', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Sesso": "sesso",
    "Età": "età",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Provincia Autonoma Bolzano / Bozen'
 'Provincia Autonoma Trento' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: età
['Non indicato' 'Fino a 17 anni' '18-24 anni' '25-34 anni' '35-44 anni'
 '45-54 anni' '55-64 anni' '65 anni e più' 'Totale' 'Non disponibile']

Colonna: periodo
[2015. 2016. 2017. 2020. 2021. 2022. 2023. 2024. 2018. 2019.]

Colonna: numero_vittime
[3.0000e+00 2.0000e+00 1.9000e+01 2.0000e+01 5.2000e+01 4.0000e+00
 5.0000e+00 6.0000e+00 2.6000e+01 3.4000e+01 1.7000e+01 1.6000e+01
 1.2000e+01 1.8000e+01 2.4000e+01 4.9000e+01 5.0000e+01 3.0000e+01
 4.7000e+01 2.8000e+01 4.2000e+01 4.8000e+01 5.6000e+01 2.9000e+01
 7.0000e+01 5.4000e+01 4.0000e+01 7.9000e+01 4.5000e+01 6.0000e+01
 7.6000e+01 6.6000e+01 5.1000e+01 8.2000e+01 4.1000e+01 6.8000e+01
 7.8000e+01 5.9000e+01 3.8000e+01 6.9000e+01 4.3000e+01 3.1000e+01
 2.5000e+01 3.3000e+01 2.3000e+01 1.0000e+01 3.7000e+01 3.5000e+01
 3.6000e+01 3.1100e+02 2.9500e+02 2.8600e+02 2.6100e+02 2.1800e+02
 5.7100e+02 5.4000e+02 2.6200e+02 4.2500e+02 4.3300e+02 4.4000e+01
 2.7000e+01 1.8900e+02 2.2400e+02 1.6000e+02 6.1000e+01 9.0000e+00
 8.8000e+01 4.1800e+02 4.7900e+02 1.2590e+03 7.8100e+02 8.7000e+01
 9.3000e+01 2.4200e+02 3.8800e+02 2.3200e+02 3.1400e+02 2.7200e+02
 4.9600e+02 4.8600e+02 5.0000e+02 5.8900e+02 6.7200e+02 1.0720e+03
 1.2970e+03 1.1230e+03 1.4190e+03 1.1170e+03 1.4020e+03 1.3840e+03
 1.3450e+03 1.5050e+03 1.6060e+03 2.1000e+03 2.0340e+03 1.8320e+03
 2.5060e+03 2.0140e+03 2.0650e+03 1.9720e+03 2.2360e+03 2.1780e+03
 2.7580e+03 2.4250e+03 2.3810e+03 3.0420e+03 2.4750e+03 1.6190e+03
 1.7310e+03 1.5630e+03 2.1190e+03 1.7670e+03 2.3500e+03 2.2870e+03
 2.0740e+03 2.5400e+03 2.2090e+03 8.9100e+02 8.8800e+02 8.1100e+02
 1.0060e+03 8.5900e+02 1.3250e+03 1.2910e+03 1.0740e+03 9.6200e+02
 8.2000e+02 6.8700e+02 7.1400e+02 6.3900e+02 7.6800e+02 6.1100e+02
 1.2500e+03 1.3330e+03 8.9500e+02 1.4310e+03 1.2690e+03 7.7700e+03
 7.8300e+03 7.7990e+03 9.3410e+03 8.4270e+03 1.5128e+04 1.5720e+04
 1.1632e+04 1.4455e+04 1.6117e+04 5.4900e+02 4.5000e+02 8.2300e+02
 9.9100e+02 6.3200e+02 3.9430e+03 4.2470e+03 1.5420e+03 9.8200e+02
 5.1600e+03 7.0000e+00 1.0000e+00 8.0000e+00 1.5000e+01 1.4030e+03
 1.0810e+03 1.1000e+01 1.3270e+03 1.0420e+03 6.3000e+01 8.1000e+01
 9.1000e+01 4.3700e+02 4.9900e+02 1.3470e+03 8.5100e+02 7.2000e+01
 9.2000e+01 9.9000e+01 2.6800e+02 4.2200e+02 2.4900e+02 3.3500e+02
 2.8800e+02 5.1400e+02 5.1000e+02 5.1700e+02 6.0700e+02 6.9000e+02
 1.1210e+03 1.1530e+03 1.4730e+03 1.1500e+03 1.4440e+03 1.4320e+03
 1.4010e+03 1.5350e+03 1.6350e+03 2.1700e+03 2.0890e+03 1.8720e+03
 2.5930e+03 2.0640e+03 2.0940e+03 2.1410e+03 2.0380e+03 2.2270e+03
 2.8400e+03 2.4790e+03 2.4220e+03 3.1180e+03 2.5260e+03 1.6970e+03
 1.7900e+03 1.6050e+03 1.8050e+03 2.4190e+03 2.3300e+03 2.1050e+03
 2.5920e+03 2.2530e+03 9.1600e+02 9.2100e+02 8.3500e+02 1.0360e+03
 8.8200e+02 1.3730e+03 1.3190e+03 1.0920e+03 9.8500e+02 8.3100e+02
 7.2400e+02 7.3700e+02 6.6300e+02 7.9600e+02 1.2850e+03 1.3670e+03
 9.1300e+02 1.4770e+03 1.3060e+03 8.0820e+03 8.1250e+03 8.0850e+03
 9.6020e+03 8.6470e+03 1.5708e+04 1.6272e+04 1.1909e+04 1.6283e+04
 1.7631e+04 5.9400e+02 4.7700e+02 8.7300e+02 1.0390e+03 6.6100e+02
 4.1410e+03 4.4820e+03 1.6040e+03 2.3630e+03 6.3620e+03 1.4000e+01
 1.3000e+01 3.2000e+01 6.4000e+01 7.1000e+01 1.0200e+02 1.0300e+02
 9.6000e+01 9.0000e+01 7.7000e+01 2.2700e+02 1.4900e+02 2.1000e+01
 8.5000e+01 5.7000e+01 6.2000e+01 1.7100e+02 1.5500e+02 2.0100e+02
 2.8100e+02 2.9600e+02 3.2500e+02 3.7700e+02 3.4100e+02 3.8200e+02
 4.2000e+02 3.9200e+02 3.7000e+02 4.1300e+02 5.7500e+02 5.1800e+02
 5.0100e+02 6.1200e+02 5.5700e+02 6.2000e+02 5.5800e+02 6.1300e+02
 5.8100e+02 6.8000e+02 6.0600e+02 6.2700e+02 7.0800e+02 7.3200e+02
 4.0300e+02 4.4400e+02 5.0600e+02 6.0300e+02 5.8300e+02 5.4500e+02
 6.4700e+02 6.4800e+02 2.0500e+02 2.4000e+02 2.0900e+02 3.3200e+02
 3.0600e+02 2.7100e+02 2.5200e+02 2.0700e+02 1.9600e+02 1.7500e+02
 2.1300e+02 1.6200e+02 3.3700e+02 2.1600e+02 2.0770e+03 2.2130e+03
 2.0750e+03 2.3200e+03 2.1590e+03 3.5720e+03 3.5320e+03 2.7940e+03
 3.3840e+03 4.3350e+03 1.1600e+02 1.1700e+02 1.7400e+02 8.9000e+01
 7.0200e+02 7.2900e+02 1.5900e+02 1.6700e+02 1.3050e+03 5.5000e+01
 9.8000e+01 6.5000e+01 6.7000e+01 1.5300e+02 1.7600e+02 1.6400e+02
 1.7700e+02 2.8900e+02 3.1000e+02 3.2900e+02 3.4600e+02 3.8700e+02
 4.3500e+02 3.9700e+02 3.8000e+02 4.2300e+02 5.8800e+02 5.3100e+02
 5.0900e+02 5.7400e+02 6.2300e+02 5.9800e+02 6.9900e+02 6.1600e+02
 7.2800e+02 7.4500e+02 4.5700e+02 4.3600e+02 5.1900e+02 4.8400e+02
 6.1800e+02 5.9100e+02 5.5100e+02 6.6000e+02 6.5800e+02 2.5100e+02
 2.6600e+02 2.4600e+02 2.7300e+02 2.6300e+02 2.1200e+02 1.9900e+02
 1.8500e+02 1.6800e+02 3.4400e+02 2.2000e+02 3.3900e+02 3.0400e+02
 2.1490e+03 2.2770e+03 2.1460e+03 2.2150e+03 3.6740e+03 3.6350e+03
 2.8450e+03 3.5500e+03 4.4750e+03 1.1800e+02 7.4000e+01 1.2800e+02
 7.2600e+02 7.6000e+02 1.6600e+02 2.2900e+02 1.3810e+03 2.2000e+01
 7.5000e+01 1.0400e+02 1.2700e+02 1.0100e+02 1.0700e+02 1.5100e+02
 1.1400e+02 1.2900e+02 1.4000e+02 1.6900e+02 1.8700e+02 1.6500e+02
 1.5700e+02 1.4600e+02 1.7300e+02 1.3800e+02 1.5000e+02 8.0000e+01
 1.0000e+02 5.8000e+01 6.4500e+02 6.8400e+02 7.0900e+02 9.5200e+02
 7.4700e+02 9.1100e+02 1.0760e+03 3.2700e+02 1.0800e+02 1.3100e+02
 1.0900e+02 1.5400e+02 1.6300e+02 1.4100e+02 1.7200e+02 1.9300e+02
 1.7900e+02 1.8100e+02 1.4400e+02 1.5200e+02 1.0600e+02 6.6900e+02
 7.0300e+02 6.5100e+02 7.2200e+02 1.0110e+03 9.8800e+02 7.5900e+02
 9.4800e+02 1.1120e+03 2.1100e+02 2.1000e+02 3.4800e+02 4.6000e+01
 3.9000e+01 5.3000e+01 1.8300e+02 2.2800e+02 1.8400e+02 3.0700e+02
 2.3100e+02 3.6000e+02 2.1500e+02 1.8800e+02 2.3400e+02 3.2200e+02
 3.1900e+02 2.3500e+02 2.7700e+02 1.4500e+02 1.1000e+02 1.1100e+02
 1.9800e+02 2.5500e+02 2.2600e+02 2.2500e+02 2.6700e+02 3.6800e+02
 3.5700e+02 3.2100e+02 4.1500e+02 3.4500e+02 3.9000e+02 3.8300e+02
 4.5100e+02 4.0200e+02 4.3100e+02 4.8200e+02 2.3300e+02 2.6500e+02
 2.3900e+02 2.9100e+02 2.7900e+02 3.7400e+02 4.2100e+02 1.3200e+02
 1.2600e+02 1.1300e+02 1.3400e+02 1.1200e+02 9.5000e+01 1.9500e+02
 2.0300e+02 1.3700e+02 1.2150e+03 1.3090e+03 1.2600e+03 1.3740e+03
 1.3340e+03 2.2630e+03 2.2640e+03 1.8020e+03 2.2040e+03 2.8770e+03
 4.4500e+02 4.5900e+02 8.6700e+02 1.5600e+02 1.1500e+02 1.2000e+02
 2.0600e+02 2.0000e+02 2.7500e+02 3.7800e+02 3.6500e+02 4.2600e+02
 3.8900e+02 3.5800e+02 3.9600e+02 3.9300e+02 4.6100e+02 4.0900e+02
 4.4200e+02 4.9300e+02 4.9000e+02 2.4800e+02 2.7400e+02 2.4400e+02
 2.9800e+02 2.8200e+02 3.6100e+02 3.3600e+02 4.3000e+02 1.3300e+02
 1.3000e+02 1.6100e+02 1.3600e+02 1.3900e+02 1.2560e+03 1.3480e+03
 1.4150e+03 1.3700e+03 2.3240e+03 2.3220e+03 1.8350e+03 2.3180e+03
 2.9690e+03 4.5800e+02 1.8000e+02 2.0800e+02 2.9900e+02 3.0000e+02
 4.3400e+02 4.1600e+02 2.8000e+02 2.5000e+02 2.8400e+02 2.9300e+02
 3.9900e+02 4.5600e+02 4.8300e+02 2.2100e+02 3.4300e+02 3.9800e+02
 4.1400e+02 1.8200e+02 1.7000e+02 1.2400e+02 1.2300e+02 1.0260e+03
 1.0090e+03 9.7500e+02 1.2550e+03 1.1960e+03 2.0050e+03 2.2780e+03
 1.7020e+03 2.1750e+03 3.0120e+03 8.3000e+01 4.2400e+02 1.1900e+02
 9.7800e+02 3.0800e+02 3.0500e+02 2.9200e+02 4.1000e+02 3.7600e+02
 3.6600e+02 4.6600e+02 2.3700e+02 2.6000e+02 3.6300e+02 3.4700e+02
 4.0700e+02 1.2200e+02 9.4000e+01 1.9400e+02 2.2200e+02 1.0750e+03
 1.0480e+03 1.2860e+03 1.2280e+03 2.0830e+03 2.3390e+03 2.2710e+03
 3.1140e+03 4.4100e+02 5.4700e+02 9.7000e+01 1.4200e+02 1.9200e+02
 1.4700e+02 1.2500e+02 1.9700e+02 4.8000e+02 4.6800e+02 4.7500e+02
 6.1400e+02 9.5600e+02 1.1410e+03 8.6100e+02 1.0140e+03 1.3930e+03
 4.7600e+02 1.3500e+02 1.7800e+02 1.4800e+02 5.0400e+02 6.2600e+02
 9.9200e+02 1.1690e+03 8.7100e+02 1.0560e+03 1.4360e+03 2.5800e+02
 5.0200e+02 2.6900e+02 7.3000e+01 8.6000e+01 2.1400e+02 1.4300e+02
 3.9400e+02 5.1300e+02 9.6500e+02 7.1000e+02 8.5300e+02 1.2080e+03
 3.6400e+02 8.4000e+01 1.8600e+02 4.4300e+02 5.2200e+02 4.9100e+02
 9.9400e+02 7.2700e+02 8.9400e+02 2.1900e+02 3.0200e+02 3.1800e+02
 2.4300e+02 3.5100e+02 4.3200e+02 4.1900e+02 4.4600e+02 5.3000e+02
 4.4700e+02 3.7900e+02 5.9600e+02 5.6600e+02 5.7900e+02 5.8400e+02
 3.7500e+02 3.4900e+02 5.3700e+02 5.2300e+02 5.6100e+02 4.9700e+02
 2.9400e+02 1.7150e+03 1.6780e+03 1.5700e+03 2.0960e+03 1.9410e+03
 3.0530e+03 3.3850e+03 2.5730e+03 3.0620e+03 3.5730e+03 7.1200e+02
 8.0400e+02 1.1340e+03 2.3600e+02 1.2100e+02 2.1700e+02 3.0900e+02
 2.5400e+02 3.2300e+02 3.5600e+02 5.4800e+02 4.6900e+02 4.6300e+02
 4.6200e+02 5.3300e+02 5.2500e+02 6.1700e+02 5.9200e+02 7.0500e+02
 5.4200e+02 3.1500e+02 3.1200e+02 1.7710e+03 1.7540e+03 1.6330e+03
 2.1530e+03 1.9890e+03 3.1830e+03 3.4870e+03 2.6430e+03 3.2130e+03
 3.7240e+03 7.4400e+02 8.2900e+02 1.2200e+03 1.0500e+02 1.5800e+02
 4.2700e+02 5.5900e+02 5.1600e+02 8.2700e+02 9.9500e+02 3.1300e+02
 5.7300e+02 8.6900e+02 8.5800e+02 6.3800e+02 1.0340e+03 2.8500e+02
 2.5600e+02 2.3000e+02 3.0100e+02 3.5300e+02 2.6400e+02 2.5900e+02
 3.4000e+02 1.9100e+02 3.6700e+02 2.7600e+02 1.9000e+02 1.0580e+03
 8.7200e+02 1.1950e+03 1.1450e+03 1.7970e+03 2.0440e+03 1.5520e+03
 1.8750e+03 2.0200e+02 2.0400e+02 2.5700e+02 3.4200e+02 2.4500e+02
 2.8700e+02 3.6900e+02 4.4800e+02 1.0450e+03 1.1010e+03 9.0500e+02
 1.2320e+03 1.1820e+03 1.8690e+03 2.1040e+03 1.5870e+03 1.9750e+03
 2.0920e+03 6.9200e+02 3.3800e+02 4.6700e+02 4.0600e+02 5.0300e+02
 6.1900e+02 5.4100e+02 5.2400e+02 3.3400e+02 4.0500e+02 4.8800e+02
 4.6500e+02 2.4100e+02 1.8100e+03 1.7100e+03 1.5410e+03 2.0370e+03
 1.8060e+03 2.8820e+03 3.0050e+03 2.1960e+03 2.3770e+03 2.8370e+03
 6.0500e+02 8.8300e+02 3.1700e+02 3.6200e+02 4.8900e+02 5.1500e+02
 6.3400e+02 4.5500e+02 5.1100e+02 4.1200e+02 4.7000e+02 2.8300e+02
 2.5300e+02 1.8830e+03 1.7760e+03 1.5930e+03 2.0990e+03 1.8490e+03
 2.9640e+03 3.0890e+03 2.2340e+03 2.4810e+03 6.2500e+02 9.5800e+02
 2.9000e+02 8.7400e+02 8.3000e+02 9.6000e+02 8.4500e+02 1.2950e+03
 1.3720e+03 9.6800e+02 1.0330e+03 1.2870e+03 3.9100e+02 2.4700e+02
 9.0400e+02 8.6200e+02 9.9000e+02 8.6400e+02 1.3230e+03 1.4070e+03
 1.0830e+03 4.9500e+02 5.9000e+02 4.6400e+02 8.7900e+02 6.3500e+02
 6.7800e+02 8.8900e+02 4.2800e+02 8.5200e+02 9.0200e+02 6.4200e+02
 7.0600e+02 9.2900e+02 3.2400e+02 3.5900e+02 7.2100e+02 7.7700e+02
 7.8400e+02 7.0000e+02 1.1970e+03 1.0880e+03 2.2300e+02 8.0200e+02
 7.4000e+02 8.0700e+02 7.1600e+02 1.1590e+03 9.2000e+02 1.1300e+03
 5.5500e+02 7.8600e+02 8.6300e+02 6.5200e+02 7.8500e+02 5.7000e+02
 5.6500e+02 8.1500e+02 6.8200e+02 8.1900e+02 3.3100e+02 3.0300e+02
 2.3800e+02 3.7300e+02 8.8700e+02 7.7800e+02 5.4400e+02 2.3950e+03
 2.1720e+03 1.4050e+03 2.5750e+03 1.2720e+03 1.2620e+03 1.2960e+03
 8.5600e+02 5.2000e+02 1.1560e+03 8.4600e+02 8.3300e+02 4.1700e+02
 9.3000e+02 5.6900e+02 2.5310e+03 2.3260e+03 1.4750e+03 3.8480e+03
 2.2190e+03 1.3550e+03 1.3920e+03 8.9200e+02 1.5610e+03 1.4000e+03]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige",
    "provincia autonoma bolzano / bozen": "bolzano",
    "provincia autonoma trento": "trento"
})


# Uniformazione minuscolo per la colonna sesso ed età
df["sesso"] = df["sesso"].str.lower().str.strip()
df["età"] = df["età"].str.lower().str.strip()


# Rimozione della voce aggregata "totale"
# da sesso e età per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["età"] != "totale")
]


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

  territorio   sesso             età  periodo  numero_vittime
0     italia  maschi    non indicato     2015               3
1     italia  maschi    non indicato     2016               2
2     italia  maschi    non indicato     2017               3
3     italia  maschi    non indicato     2020               3
4     italia  maschi    non indicato     2021              19
5     italia  maschi    non indicato     2022              20
6     italia  maschi    non indicato     2023              52
7     italia  maschi    non indicato     2024              52
8     italia  maschi  fino a 17 anni     2015               4
9     italia  maschi  fino a 17 anni     2016               3

<class 'pandas.core.frame.DataFrame'>
Index: 4024 entries, 0 to 7241
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   territorio      4024 non-null   object
 1   sesso           4024 non-null   object
 2   età             4024 non-null   object
 3   periodo         4024 non-null   int64
 4   numero_vittime  4024 non-null   int64
dtypes: int64(2), object(3)
memory usage: 188.6+ KB

Missing values per colonna:

territorio        0
sesso             0
età               0
periodo           0
numero_vittime    0
dtype: int64

Numero valori unici per colonna:

numero_vittime    483
territorio         28
periodo            10
età                 9
sesso               3
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'bolzano' 'trento' 'veneto' 'friuli venezia giulia'
 'emilia romagna' 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud'
 'abruzzo' 'molise' 'campania' 'puglia' 'basilicata' 'calabria' 'isole'
 'sicilia' 'sardegna' 'non indicato']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: età
['non indicato' 'fino a 17 anni' '18-24 anni' '25-34 anni' '35-44 anni'
 '45-54 anni' '55-64 anni' '65 anni e più' 'non disponibile']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[   3    2   19   20   52    4    5    6   26   34   17   16   12   18
   24   49   50   30   47   28   42   48   56   29   70   54   40   79
   45   60   76   66   51   82   41   68   78   59   38   69   43   31
   25   33   23   10   37   35   36   44   27  189  224  160   61    9
   88  418  479 1259  781   87   93  242  388  232  314  272  496  486
  500  589  672 1072 1297 1123 1419 1117 1402 1384 1345 1505 1606 2100
 2034 1832 2506 2014 2065 1972 2236 2178 2758 2425 2381 3042 2475 1619
 1731 1563 2119 1767 2350 2287 2074 2540 2209  891  888  811 1006  859
 1325 1291 1074  962  820  687  714  639  768  611 1250 1333  895 1431
 1269  549  450  823  991  632 3943 4247 1542  982 5160    7    1    8
   11   15 1327 1042   14   13   32   77  227  149   21   85   57   62
   64  171  155  201  281  296  325  377  341  382  420  392  370  413
  575  518  501  612  594  557  620  558  613  581  680  606  627  708
  732  403  444  425  506  477  603  583  545  647  648  249  261  205
  240  209  332  306  271  252  207  196  175  213  162  337  216  295
  116   71  117  174   89  702  729  159  167 1305   55   22   65   75
  102  104  127  101  107  151  114  129  140  169  187  165  177  153
  157  146  173  138  150   80   99   91   72  100   58   63   92  199
  327   46   39   53  145  110  111  184  198  255  235  226  262  251
  225  267  368  357  321  415  346  345  390  383  451  402  431  482
  233  265  239  291  279  374  421  132  126  113  183  163  154  134
  112   95  195  203  137  445  459  867   74  103  109  210  180  208
  299  300  434  416  280  250  289  284  293  399  361  456  483  221
  179  274  234  343  398  414  120  182  170  133  124  123  193   83
  424  517  119  115  978   96   97  131  142  181  144  192  147  125
  161  197  248  476   73   86  135  118  139  141  214  143  156   81
  364   84  219  130   94  302  318  243  351  432  419  446  530  457
  447  379  522  509  596  566  579  690  584  375  349  537  423  523
  561  497  607  294  260  206  322  305  304  712  804 1134  105  122
  106  158  136  313  121  231  329  237  259  275  212  311  288  353
  435  340  211  220  191  312  367  276  188   90  152  190  128  185
  531  645  168  108  148  178  338  342  490  467  406  503  493  619
  541  524  548  427  334  405  488  514  465  441  241  194  273  605
  883  172  268  254  244  217  166  222   67  391  258  218  176  263
  430  230 1262 1296  856  520  833]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/vittime.età.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/vittime.età.csv