In [1]:
import pandas as pd

df = pd.read_csv("../raw/Orientamento_sessuale.csv")

df.head()

,FREQ,Frequenza,REF_AREA,Territorio,DATA_TYPE,Indicatore,SEX,Sesso,SEXUAL_ORIENTATION,Orientamento sessuale,TIME_PERIOD,Osservazione,OBS_STATUS,Stato_osservazione
0,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,OMOX,Omosessuale,2015.0,24.0,NaN,NaN
1,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,OMOX,Omosessuale,2016.0,34.0,NaN,NaN
2,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,OMOX,Omosessuale,2017.0,56.0,NaN,NaN
3,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,OMOX,Omosessuale,2018.0,36.0,NaN,NaN
4,A,Annuale,IT,Italia,USERS,Utenti del 1522,M,Maschi,OMOX,Omosessuale,2019.0,45.0,NaN,NaN

In [2]:
# Per ogni colonna: numero di valori unici + elenco valori

for col in df.columns:
    print("=" * 60)
    print(f"Colonna: {col}")
    print(f"Numero valori unici: {df[col].nunique(dropna=False)}")
    print("Valori unici:")
    print(df[col].unique())
    print("\n")

============================================================
Colonna: FREQ
Numero valori unici: 61
Valori unici:
['A'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,MISSING,Missing,2023,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,MISSING,Missing,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,OTHER,Altro o non indicato,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2015,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2016,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2017,1,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2018,3,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2019,2,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2020,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2021,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2022,4,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2023,10,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,M,Maschi,TOTAL,Totale,2024,6,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,MISSING,Missing,2023,30,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,MISSING,Missing,2024,60,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2015,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2016,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2018,19,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2019,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2020,25,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2021,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,OTHER,Altro o non indicato,2022,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2015,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2016,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2017,16,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2018,19,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2019,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2020,25,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2021,13,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2022,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2023,30,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,F,Femmine,TOTAL,Totale,2024,60,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,MISSING,Missing,2023,40,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,MISSING,Missing,2024,66,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2015,19,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2016,18,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2017,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2018,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2019,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2020,29,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2021,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,OTHER,Altro o non indicato,2022,26,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2015,19,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2016,18,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2017,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2018,22,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2019,15,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2020,29,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2021,17,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2022,26,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2023,40,,'
 'A,Annuale,ITC2,\'Valle d"\'Aosta / Vallée d"\'Aoste\',USERS,Utenti del 1522,T,Totale,TOTAL,Totale,2024,66,,']


============================================================
Colonna: Frequenza
Numero valori unici: 2
Valori unici:
['Annuale' nan]


============================================================
Colonna: REF_AREA
Numero valori unici: 27
Valori unici:
['IT' 'ITC' 'ITC1' nan 'ITC3' 'ITC4' 'ITD' 'ITDA' 'ITD3' 'ITD4' 'ITD5'
 'ITE' 'ITE1' 'ITE2' 'ITE3' 'ITE4' 'ITF' 'ITF1' 'ITF2' 'ITF3' 'ITF4'
 'ITF5' 'ITF6' 'ITG' 'ITG1' 'ITG2' 'ITNI']


============================================================
Colonna: Territorio
Numero valori unici: 27
Valori unici:
['Italia' 'Nord-ovest' 'Piemonte' nan 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']


============================================================
Colonna: DATA_TYPE
Numero valori unici: 2
Valori unici:
['USERS' nan]


============================================================
Colonna: Indicatore
Numero valori unici: 2
Valori unici:
['Utenti del 1522' nan]


============================================================
Colonna: SEX
Numero valori unici: 5
Valori unici:
['M' 'F' 'NRP' 'T' nan]


============================================================
Colonna: Sesso
Numero valori unici: 5
Valori unici:
['Maschi' 'Femmine' 'Non indicato' 'Totale' nan]


============================================================
Colonna: SEXUAL_ORIENTATION
Numero valori unici: 6
Valori unici:
['OMOX' 'TRANS' 'MISSING' 'OTHER' 'TOTAL' nan]


============================================================
Colonna: Orientamento sessuale
Numero valori unici: 6
Valori unici:
['Omosessuale' 'Transessuale' 'Missing' 'Altro o non indicato' 'Totale'
 nan]


============================================================
Colonna: TIME_PERIOD
Numero valori unici: 11
Valori unici:
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.   nan]


============================================================
Colonna: Osservazione
Numero valori unici: 1003
Valori unici:
[   24.    34.    56. ...  6921. 10274.  8771.]


============================================================
Colonna: OBS_STATUS
Numero valori unici: 1
Valori unici:
[nan]


============================================================
Colonna: Stato_osservazione
Numero valori unici: 1
Valori unici:
[nan]

In [3]:
# Rimozione colonne non informative o ridondanti:
# - colonne costanti (un solo valore per tutto il dataset)
# - colonne duplicate sul piano informativo
# - colonne completamente vuote

cols_to_drop = [
    "FREQ",               
    "Frequenza",          
    "REF_AREA",          
    "DATA_TYPE",                  
    "SEX",                
    "SEXUAL_ORIENTATION",     
    "OBS_STATUS",         
    "Stato_osservazione" 
]

df = df.drop(columns=cols_to_drop)

# Verifica struttura finale
print("Nuova shape:", df.shape)
print("Colonne rimanenti:", df.columns.tolist())

Nuova shape: (2640, 6)
Colonne rimanenti: ['Territorio', 'Indicatore', 'Sesso', 'Orientamento sessuale', 'TIME_PERIOD', 'Osservazione']

In [4]:
# Standardizzazione nomi colonne:
# - tutto minuscolo
# - nomi più chiari e coerenti

df = df.rename(columns={
    "Territorio": "territorio",
    "Indicatore": "canale_segnalazione",
    "Sesso": "sesso",
    "Orientamento sessuale": "orientamento_sessuale",
    "TIME_PERIOD": "periodo",
    "Osservazione": "numero_vittime"
})


# Eliminazione delle righe completamente vuote 
df = df.dropna(how="all")

# Stampa delle colonne e dei valori unici che contengono
for col in df.columns:
    print("\nColonna:", col)
    print(df[col].unique())

Colonna: territorio
['Italia' 'Nord-ovest' 'Piemonte' 'Liguria' 'Lombardia' 'Nord-est'
 'Trentino Alto Adige / Südtirol' 'Veneto' 'Friuli-Venezia Giulia'
 'Emilia-Romagna' 'Centro' 'Toscana' 'Umbria' 'Marche' 'Lazio' 'Sud'
 'Abruzzo' 'Molise' 'Campania' 'Puglia' 'Basilicata' 'Calabria' 'Isole'
 'Sicilia' 'Sardegna' 'Non indicato']

Colonna: canale_segnalazione
['Utenti del 1522']

Colonna: sesso
['Maschi' 'Femmine' 'Non indicato' 'Totale']

Colonna: orientamento_sessuale
['Omosessuale' 'Transessuale' 'Missing' 'Altro o non indicato' 'Totale']

Colonna: periodo
[2015. 2016. 2017. 2018. 2019. 2020. 2021. 2022. 2023. 2024.]

Colonna: numero_vittime
[   24.    34.    56. ...  6921. 10274.  8771.]

In [5]:
# Pulizia colonna territorio:
# - uniformazione minuscolo
# - correzione denominazioni incoerenti / verbose

df["territorio"] = (
    df["territorio"]
    .str.lower()
    .str.strip()
    .str.replace("-", " ", regex=False)
)

df["territorio"] = df["territorio"].replace({
    "trentino alto adige / südtirol": "trentino alto adige"
})


# Uniformazione minuscolo per la colonna sesso e orientamento_sessuale
df["sesso"] = df["sesso"].str.lower().str.strip()
df["orientamento_sessuale"] = df["orientamento_sessuale"].str.lower().str.strip()


# Rimozione della voce aggregata "totale" 
# da sesso e orientamento_sessuale per evitare doppio conteggio

df = df[
    (df["sesso"] != "totale") &
    (df["orientamento_sessuale"] != "totale")
]


# Conversione delle colonne numeriche da float a integer

df["periodo"] = df["periodo"].astype(int)
df["numero_vittime"] = df["numero_vittime"].astype(int)


# Verifica finale post-pulizia (struttura + qualità base)

# 1) Dimensioni e info colonne
display(df.head(10))
df.info()

# 2) Tipi e missing
print("\nMissing values per colonna:")
display(df.isna().sum().sort_values(ascending=False))

# 3) Valori unici (conteggio) per colonna
print("\nNumero valori unici per colonna:")
display(df.nunique(dropna=False).sort_values(ascending=False))

# 4) Check duplicati (righe identiche)
print("\nRighe duplicate (identiche su tutte le colonne):", df.duplicated().sum())

# 5) Valori distinti per ogni colonna
for col in df.columns:
    print("\nColonna:", col)
    
    if col == "periodo":
        print(sorted(df[col].astype(int).unique().tolist()))
    else:
        print(df[col].unique())

,territorio,canale_segnalazione,sesso,orientamento_sessuale,periodo,numero_vittime
0,italia,Utenti del 1522,maschi,omosessuale,2015,24
1,italia,Utenti del 1522,maschi,omosessuale,2016,34
2,italia,Utenti del 1522,maschi,omosessuale,2017,56
3,italia,Utenti del 1522,maschi,omosessuale,2018,36
4,italia,Utenti del 1522,maschi,omosessuale,2019,45
5,italia,Utenti del 1522,maschi,omosessuale,2020,91
6,italia,Utenti del 1522,maschi,omosessuale,2021,92
7,italia,Utenti del 1522,maschi,omosessuale,2022,77
8,italia,Utenti del 1522,maschi,transessuale,2015,14
9,italia,Utenti del 1522,maschi,transessuale,2016,12

<class 'pandas.core.frame.DataFrame'>
Index: 1144 entries, 0 to 2596
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   territorio             1144 non-null   object
 1   canale_segnalazione    1144 non-null   object
 2   sesso                  1144 non-null   object
 3   orientamento_sessuale  1144 non-null   object
 4   periodo                1144 non-null   int64
 5   numero_vittime         1144 non-null   int64
dtypes: int64(2), object(4)
memory usage: 62.6+ KB

Missing values per colonna:

territorio               0
canale_segnalazione      0
sesso                    0
orientamento_sessuale    0
periodo                  0
numero_vittime           0
dtype: int64

Numero valori unici per colonna:

numero_vittime           442
territorio                26
periodo                   10
orientamento_sessuale      4
sesso                      3
canale_segnalazione        1
dtype: int64

Righe duplicate (identiche su tutte le colonne): 0

Colonna: territorio
['italia' 'nord ovest' 'piemonte' 'liguria' 'lombardia' 'nord est'
 'trentino alto adige' 'veneto' 'friuli venezia giulia' 'emilia romagna'
 'centro' 'toscana' 'umbria' 'marche' 'lazio' 'sud' 'abruzzo' 'molise'
 'campania' 'puglia' 'basilicata' 'calabria' 'isole' 'sicilia' 'sardegna'
 'non indicato']

Colonna: canale_segnalazione
['Utenti del 1522']

Colonna: sesso
['maschi' 'femmine' 'non indicato']

Colonna: orientamento_sessuale
['omosessuale' 'transessuale' 'missing' 'altro o non indicato']

Colonna: periodo
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

Colonna: numero_vittime
[   24    34    56    36    45    91    92    77    14    12    32    15
    60    31    25  6154  8278  2166  1648  2057  2516  2290  3275  3901
  3755    13    20    16    28    89    81    44    40   183   125    70
 41235 52166 17452 15887 15441 20629 18903 28021 31821 28445  4324  4604
     1     2     9    11    10    17     5     3   931  1141   431   406
   456   479   484   621   556   609     6     4    21  7692 10475  4359
  4188  3756  4789  4519  5935  5787  5446    42   239   299   149   140
   172   133   148   165   160   161     8  2156  2734  1364  1315  1104
  1417  1344  1690  1602  1499   105   103    47    29    38    58    53
   654   874   501   463   363   482   453   541   587   525     7   577
   733   233   236   254   296   394   350   391    22  4852  6807  2477
  2393  2273  2871  2709  3679  3585  3400    27   682   860   267   201
   206   294   306   389   429   362  5930  7612  2296  1992  1846  2649
  2775  3573  3934  3663    26    62   307   388   114   113    79   181
   207   252   218   303   382   118   147   150   186   209   177  2361
  3289  1082   865   899  1207  1333  1614  1881  1702    94    30   438
   240   224   190   290   256   314   315   297   238   337   102    82
    72   107   120   145   129  2824  3326   790   678   987  1005  1438
  1486  1446    18    19   927  1181   392   318   368   451   462   622
   553    39  7468  9201  3633  3302  3127  4446  4329  5400  5834  5264
    50   247   317    78    90   109   112   111   154  1695  2384   800
   629   836  1158  1208  1375  1423  1297    41   464   510   216   197
   175   221   235   288   309    83    54    35    48    43    64   656
   839   443   354   454   386   509   505   688   242   174   214   270
   289   340    33  4653  5468  2174  2070  1762  2594  2514  3281  3536
  3153   849  1069   548   335   401   542   545   534  5771  7473  4053
  3463  3070  4336  3935  5095  5394  4779    37    99    55    46   655
   702   448   405   494   419   473   528   472   132    86    68    67
    88   351   477   158   213   249   244   243  2545  3489  1911  1663
  2064  1899  2387  2548  2121   230   313   168   159  1562  2240  1067
   904   793  1185   992  1422  1469  1312   126   138   153   123    57
    75    63   694   729   458   293   430   437   608   633   344   452
   205   257   222  2307  3008  1740  1766  1479  1769  1565  2033  2251
  2023   330   169   127   163   187   164  2148  1220  1239  1023  1116
  1482  1543  1362   122    84    76   705   520   527   549   449   551
   708   661  2421  3575   292   220   421   842  1572  1429 12067 14397
  1371  1176  2163  2640  1780  5985  8621  7270  4151  4480]

In [6]:
# Salvataggio dataset pulito

output_path = "../data_clean/Orientamento_sessuale.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("File salvato in:", output_path)

File salvato in: ../data_clean/Orientamento_sessuale.csv